### ISSUE TITLE
Notification: Feed back of LTFS format Spec 2.5

### ISSUE THREAD

**Issue by piste-jp-ibm** [LinearTapeFileSystem/ltfs#122]
This is not an actual issue but just a notification for all person interning into the LTFS project and contributors.

As I described into README, next generation LTFS format, LTFS Format Spec 2.5 is under public review. You can check it [here]( https://www.snia.org/sites/default/files/technical_work/PublicReview/LTFS_Format_2%205%200_draft_rev_%201_190220.pdf). And also you can make any feedback from the SNIA site (http://snia.org/tech_activities/publicreview/#ltfs).

**Comment by piste-jp-ibm** [comment]
Dear contributors,

Next generation LTFS format, LTFS Format Spec 2.5 is under public review now. You can check it [here]( https://www.snia.org/sites/default/files/technical_work/PublicReview/LTFS_Format_2%205%200_draft_rev_%201_190220.pdf). And also you can make any feedback from the SNIA site (http://snia.org/tech_activities/publicreview/#ltfs).

@kend , @manu0401 , @rzerres , @lucasvr , @kev, @DavidAPease

**Comment by lucasvr** [comment]
Hi, Abe-san. Thanks for the notification. I've also received an email from @DavidAPease last week with a request for review and replied to him earlier this evening with my observations and suggestions. Best regards!

**Comment by piste-jp-ibm** [comment]
LTFS Format Spec 2.5 was released !! 

Check https://www.snia.org/sites/default/files/technical_work/LTFS/LTFS_Format_v2.5_Technical_Position.pdf
