### ISSUE TITLE
can't install on CENTOS 7 because of UUID

### ISSUE THREAD

**Issue by dTrimon** [LinearTapeFileSystem/ltfs#127]
Hello,
I'm trying to install ltfs on centos 7 I tried  v2.4.1 and master But the same proble occur:

    checking for UUID_MODULE... no
    configure: error: Package requirements (uuid >= 1.36) were not met:
    No package 'uuid' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.

I've installed  uuid version 1.6 can't find a higher one. Thanks for your help

**Comment by piste-jp-ibm** [comment]
Hi, 

Could you confirm `libuuid-devel` package is installed?

**Comment by dTrimon** [comment]
Ok that was it Thanks,
Seems we also need net-snmp-devel which is not tested!

**Comment by piste-jp-ibm** [comment]
You can build a version which doesn't support SNMP with the `--disable-snmp` option.

The LTFS has many configureable build options. Check with "./configure --help" for your requirement.

**Comment by rdp** [comment]
For followers, NB that you need `libuuid-devel` and not `uuid-devel` it seems...
