### ISSUE TITLE
How to mount hp Ultrium lto5 tape dirver

### ISSUE THREAD

**Issue by idreamerhx** [LinearTapeFileSystem/ltfs#136]
**Is your feature request related to a problem? Please describe.**

Does this project support HP EH957/EH958.
I install hp ltt and ltfs  on archlinux using yaourt:
aur/ltfs 2.4.0.2-1
aur/hpltt 4.27-1

but ltfs shows:

39f5 LTFS14000I LTFS starting, LTFS version 2.4.0.2, log level 2.
39f5 LTFS14058I LTFS Format Specification version 2.4.0.
39f5 LTFS14104I Launched by "ltfs".
39f5 LTFS14105I This binary is built for Linux (x86_64).
39f5 LTFS14106I GCC version is 8.3.0.
39f5 LTFS17087I Kernel version: Linux version 5.1.5-arch1-2-ARCH (builduser@heftig-23132) (gcc version 8.3.0 (GCC)) #1 SMP PREEMPT Mon May 27 03:37:39 UTC 2019 i386.
39f5 LTFS17089I Distribution: NAME="Arch Linux".
39f5 LTFS17089I Distribution: .
39f5 LTFS14063I Sync type is "time", Sync time is 300 sec.
39f5 LTFS17085I Plugin: Loading "sg" tape backend.
39f5 LTFS17085I Plugin: Loading "unified" iosched backend.
39f5 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
39f5 LTFS30209I Opening a device through sg-ibmtape driver (/dev/sg0).
39f5 LTFS30213I Unsupported Drive 'Ultrium 5-SCSI  '.
39f5 LTFS12012E Cannot open device: failed backend open call.
39f5 LTFS10004E Cannot open device '/dev/sg0'.

**Describe the solution you'd like**

Should I install hp spefic driver? or ltfs not support hp lto5 tape driver.

**Describe alternatives you've considered**

**Additional context**

**Comment by piste-jp-ibm** [comment]
Sorry, the current code only supports IBM drives. See README.md (https://github.com/LinearTapeFileSystem/ltfs#supported-tape-drives).

The reason is quite simple. I don't have any drives except IBM drives. I hope someone contributes it someday.

**Comment by Sector14** [comment]
@piste-jp-ibm Would this also exclude the Quantum tape drives? When using their version of mkltfs and ltfs I noticed in the mount output that it's using the sg-ibmtape driver which appears to be the driver you use for the supported IBM tapes.

`ltfs /mnt/ltfs -o devname=/dev/sg0 
1668 LTFS14000I LTFS starting, LTFS version 2.4.0.2, log level 2.
1668 LTFS14058I LTFS Format Specification version 2.4.0.
1668 LTFS14104I Launched by "ltfs /mnt/ltfs -o devname=/dev/sg0".
1668 LTFS14105I This binary is built for Linux (x86_64).
1668 LTFS14106I GCC version is 8.3.0.
1668 LTFS17087I Kernel version: Linux version 5.3.0-0.bpo.2-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 5.3.9-2~bpo10+1 (2019-11-13) i386.
1668 LTFS17089I Distribution: PRETTY_NAME="Debian GNU/Linux 10 (buster)".
1668 LTFS14063I Sync type is "time", Sync time is 300 sec.
1668 LTFS17085I Plugin: Loading "sg" tape backend.
1668 LTFS17085I Plugin: Loading "unified" iosched backend.
1668 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
1668 LTFS30209I Opening a device through sg-ibmtape driver (/dev/sg0).
1668 LTFS30207I Vendor ID is QUANTUM .
1668 LTFS30208I Product ID is ULTRIUM 5       .
1668 LTFS30214I Firmware revision is 3210.
1668 LTFS30215I Drive serial is HU140612KJ.
1668 LTFS17160I Maximum device block size is 1048576.
1668 LTFS11330I Loading cartridge.
1668 LTFS11332I Load successful.
1668 LTFS17157I Changing the drive setting to append-anywhere mode.
1668 LTFS11005I Mounting the volume.
1668 LTFS17227I Tape attribute: Vendor = QUANTUM .
1668 LTFS17227I Tape attribute: Application Name = LTFS                            .
1668 LTFS17227I Tape attribute: Application Version = 2.4.0.2 .
1668 LTFS17227I Tape attribute: Medium Label = .
1668 LTFS17228I Tape attribute: Text Localization ID = 0x81.
1668 LTFS17227I Tape attribute: Barcode =                                 .
1668 LTFS17227I Tape attribute: Application Format Version = 2.4.0           .
1668 LTFS17228I Tape attribute: Volume Lock Status = 0x00.
1668 LTFS17227I Tape attribute: Media Pool name = .
1668 LTFS14111I Initial setup completed successfully.
1668 LTFS14112I Invoke 'mount' command to check the result of final setup.
1668 LTFS14113I Specified mount point is listed if succeeded.`

I've not looked into the code of this project yet, but what would be the relevant areas to look at as far as adding support for a drive like Quantums if it's using a currently supported gb-ibmtape driver?

**Comment by piste-jp-ibm** [comment]
@Sector14,

I didn't realize this thing at all. And I never received any PR from the guy working in Quantum yet.

On the other hand, I never added Quantum drive support in this project at all. I guess they added their own code into their source tree based on this project, but I never received any feedback at all.

**Comment by scsirob** [comment]
> On the other hand, I never added Quantum drive support in this project at all. I guess they added their own code into their source tree based on this project, but I never received any feedback at all.

Quantum most likely hasn't done anything to the IBM code. It just works. So do HP drives.

I've played with both HP's and IBM's LTFS implementation. Nothing vendor-specific is needed to support each other's drives if the implementation sticks with the T10 SSC SCSI reference. All LTO vendors and products comply with that standard. They all support the necessary read/write/space/locate commands, log- and mode sense pages to work properly. They all support tape partitioning the same way. As long as the driver doesn't deliberately use vendor-unique features (which isn't needed to implement LTFS), the driver will work with any LTO-5 and up drive.

Some implementations make unnecessary deviations by calling vendor-specific commands, simply to cause incompatibility. HP's LTFS driver has a list of accepted Inquiry entries they check against (HP native, plus some OEMs) and the driver insists on using an HP-specific diagnostics dump command that IBM doesn't have, but simply disabling that command makes the IBM drive work just fine with their code.

The whole point of LTFS is to guarantee interoperability across brands and systems. The need to have drive-specific drivers is kinda backwards to that principle.

**Comment by piste-jp-ibm** [comment]
It is not enough to check only T10 SSC SCSI documents, we need to check drive's own SCSI specs.

The point is not vendor unique commands. We never uses vendor unique commands at all. The points are many tiny things like below. 

1. Difference of vendor specific sense codes
2. Difference of supported log pages
3. Tiny difference of field meaning of log pages
4. Difference of supported mode pages
5. Tiny difference of field meaning of mode pages

And do you have any idea to support other vendor's drives? At this time, 

- I'm an employee of IBM (See my profile)
- I have only IBM drives for developing this project

My preference is someone who have drives develops the code, confirms it works and then sends a PR to this project.

**Comment by Sector14** [comment]
fwiw Quantum provide their source modifications [here](https://www.quantum.com/serviceandsupport/opensource/ltfs/index.aspx). 

I only had a cursory look at a diff of their changes but it largely looked like addition of a new product code and a scattering of IFDEFs where product codes are used to check for capabilities. Whether a direct merge is a good idea though, I'm not sure, might be better to handle the cap checks in a way that doesn't explode with more IFDEFs as additional brands/models are added.

On another note, encryption does not appear to be supported, although afaik the drive itself being an LTO5 should support it?

Not sure I'll have sufficient downtime to look into a proper comparison for some time although more than happy to test if anyone else is able to do add support in the mean time though.

**Comment by piste-jp-ibm** [comment]
Now I'm working on supporting HP drives. @idreamerhx, please try `multi-vendor` branch if you are interested into running LTFS on HP drives.

`https://github.com/LinearTapeFileSystem/ltfs/tree/multi-vendor`

**Comment by piste-jp-ibm** [comment]
@Sector14 , @scsirob  ,

For Quantum drives, I will add something after `multi-vendor` branch is merged to `master`.

I think almost same method shall work for Quantum drives.

**Comment by scsirob** [comment]
That is excellent news, thank you for your efforts! I can test both IBM and HP side by side. No access to Quantum unfortunately.

**Comment by Sector14** [comment]
I have a Quantum drive I can run some tests against.

**Comment by piste-jp-ibm** [comment]
@Sector14 ,Thank you for your information.

I will touch you when the experimental code for Quantum is available. The code will be available after merging `multi-vendor` branch into master. 

Please wait a moment.

**Comment by Sector14** [comment]
> @Sector14 ,Thank you for your information.
> 
> I will touch you when the experimental code for Quantum is available. The code will be available after merging `multi-vendor` branch into master.
> 
> Please wait a moment.

I noticed there's been a few commits related to the Quantum drive. Is this far enough along to be worth building and giving it a test run? Or is there still further work required?

**Comment by piste-jp-ibm** [comment]
> > @Sector14 ,Thank you for your information.
> > I will touch you when the experimental code for Quantum is available. The code will be available after merging `multi-vendor` branch into master.
> > Please wait a moment.
> 
> I noticed there's been a few commits related to the Quantum drive. Is this far enough along to be worth building and giving it a test run? Or is there still further work required?

 Sorry I might forget to notify you. I think it is ready. I merged the #209 for first Quantum support. 

One thing you need to take care is the code only supports Quantum's Half Height drives. As you see like the link below, there are some other 2 drives (denend on another repository's info). It would be Full Height drives but I didn't include there definitions in #209.

https://github.com/royalmoose/ltfs-quantum/blob/0a41225db984035e2927d07554b7a5f87bbc01f2/src/tape_drivers/ibm_tape.c#L257:L262
