### ISSUE TITLE
homebrew formula for ltfs

### ISSUE THREAD

**Issue by dericed** [LinearTapeFileSystem/ltfs#180]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A hope for `brew install ltfs` or `brew install some-tap/ltfs` to work.

**Describe alternatives you've considered**
Following the installation instructions of the readme.

**Additional context**
It seems like the installation instructions put a lot of consideration to homebrew environments but I don't see a formula for ltfs itself. I've started a draft of that work at https://github.com/amiaopensource/homebrew-amiaos/pull/220 but am stuck on an installation issue. I wanted to share that here in case any others are interested in contributing towards having an ltfs brew formula.

**Comment by piste-jp-ibm** [comment]
Hi, 

Actually packaging things were already described into the Wiki (https://github.com/LinearTapeFileSystem/ltfs/wiki/Quick-start#packaging).

And the actual formula was already provided by piste2750.

[piste2750/homebrew-ltfs](https://github.com/piste2750/homebrew-ltfs)

**Comment by piste-jp-ibm** [comment]
Close this issue because we don't have any comment about 1 month.

Please reopen this if you cannot resolve the problem yet.
