### ISSUE TITLE
EOD warning due to buffer too small

### ISSUE THREAD

**Issue by scsirob** [LinearTapeFileSystem/ltfs#183]
**Describe the bug**
I am seeing the following warning while mounting a tape:
LTFS30238W Cannot get EOD status: failed to parse the log page.

**To Reproduce**
Take LTO6 drive
Insert LTO6 LTFS mounted volume
Mount tape
Observe warning even though tape mounts OK.

**Expected behavior**
No warnings

**Desktop (please complete the following information):**
 - OS: CentOS 7, kernel 3.10.0-1062.4.3.el7.x86_64

**Additional context**
In ./src/tape_drivers/linux/sg-ibmtape/sg_ibmtape.c
sg_ibmtape_get_eod_status() checks validity of EOD capacities. It retrieves Log Sense page 0x17 and checks parameter 0x0203 "Approximate used native capacity of partition(s)"
It parses the log page and then checks the size of the parameter against the buffer size. `(param_size != sizeof(buf)`

The buffer is 16 bytes in size. `unsigned char buf[16];`
The LTO-6 drive returns 32 bytes for that parameter, as it supports up to 4 partitions and needs 8 bytes per partition. This test will only pass for LTO-5 which supports only 2 partitions.
Partial dump of the IBM Log Sense page 0x17:
```
01c0: 03 FF FF FF FF 02 03 43 - 20 07 00 00 00 FF FF FF   .......C  .......
01d0: FF 07 00 00 01 FF FF FF - FF 07 00 00 02 FF FF FF   ........ ........
01e0: FF 07 00 00 03 FF FF FF - FF 02 04 43 20 07 00 00   ........ ...C ...
01f0: 00 FF FF FF FF 07 00 00 - 01 FF FF FF FF 07 00 00   ........ ........
0200: 02 FF FF FF FF 07 00 00 - 03 FF FF FF FF            ........ .....

```

**Comment by piste-jp-ibm** [comment]
I cannot recreate the problem on my bench. Could you tell me what drive do you use?

```
OS:    RHEL7 (3.10.0-514.10.2.el7.x86_64)
Drive: IBM ULT3580-TD6 (LTO6 FF)
FW:    H4T0
Tape:  IBM LTO6 tape cartridge (LTFS formatted - 2 partitions)
```

The response of logsense(pc=0x01, page=0x17,  param=0x203) is as follows. At least, my LTO6 drive only returns information of partitions that is existed on the tape. (In other words, the drive returns only 2 partitions info when there are only 2 partitions on the tape even if the tape supports 4 partitons.)

```
          0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F   0123456789ABCDEF
         -----------------------------------------------   ----------------
000000   02 03 43 10 07 00 00 00 00 00 00 07 07 00 00 01   ..C.............
000010   00 00 00 04
```

**Comment by scsirob** [comment]
My drive has older firmware, it seems:
```
Tape Drive identified as LTO6 (IBM)
/dev/st0 - Vendor  ID: IBM
/dev/st0 - Product ID: ULTRIUM-HH6
/dev/st0 - Firmware  : F4DM
```
Unfortunately I have not been able to reproduce the behaviour. Not sure if it has anything to do with the issue, but this is a library drive that I inherited. It presents an unititialized media changer to Linux as well (Nothing attached to the ADI)
```
[root@vtape ~]# lsscsi
[0:0:0:0]    disk    ATA      WDC WDS240G1G0B- 1000  /dev/sda
[2:0:0:0]    disk    ATA      WDC WD3000F9YZ-0 1A01  /dev/sdb
[3:0:0:0]    disk    ATA      WDC WD1003FBYX-0 1V01  /dev/sdc
[6:0:0:0]    tape    IBM      ULTRIUM-HH6      F4DM  /dev/st0
[6:0:0:1]    mediumx UNKNOWN  NOT INITIALIZED        /dev/sch0
[8:0:0:0]    tape    HP       Ultrium 5-SCSI   1911  /dev/st1
[8:0:0:1]    tape    HP       Ultrium 5-SCSI   1912  /dev/st2
[8:0:0:2]    mediumx HP       MSL G3 Series    1910  /dev/sch1

```
I'll try to reproduce and report back later.

**Comment by piste-jp-ibm** [comment]
Please reopen when you see the problem again.
