### ISSUE TITLE
is there any ltfs software that works for Ubuntu-18.04?

### ISSUE THREAD

**Issue by ss4858** [LinearTapeFileSystem/ltfs#189]
I am having trouble formatting tape on an ULTRIUM-HH8 tape drive attached to a computer having UBUNTU-18.04. Error is as follows:

**sudo mkltfs -d /dev/sg1**
LTFS15000I Starting mkltfs, LTFS version 2.4.2.0 (Prelim), log level 2.
LTFS15041I Launched by "mkltfs -d /dev/sg1".
LTFS15042I This binary is built for Linux (x86_64).
LTFS15043I GCC version is 7.4.0.
LTFS17087I Kernel version: Linux version 4.15.0-88-generic (buildd@lgw01-amd64-036) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 i386.
LTFS17089I Distribution: NAME="Ubuntu".
LTFS17089I Distribution: DISTRIB_ID=Ubuntu.
LTFS15003I Formatting device '/dev/sg1'.
LTFS15004I LTFS volume blocksize: 524288.
LTFS15005I Index partition placement policy: None.

LTFS11337I Update index-dirty flag (1) - NO_BARCODE (0x0x561e60511c10).
LTFS17085I Plugin: Loading "sg" tape backend.
LTFS30209I Opening a device through sg-ibmtape driver (/dev/sg1).
LTFS30213I Unsupported Drive 'ULTRIUM-HH8     '.
Segmentation fault

**Comment by mrichmon** [comment]
It looks like you are not using the IBM lintape device driver.

**Comment by piste-jp-ibm** [comment]
Now, LTFS is using the sg driver by default. So the command looks good to me.

I think this is very close to issue #184. Please provide a output of `sudo ltfs -o device_list`. I think you are not using an IBM drive.

**Comment by ss4858** [comment]
sudo ltfs -o device_list outputs:

3a5b LTFS14000I LTFS starting, LTFS version 2.4.2.0 (Prelim), log level 2.
3a5b LTFS14058I LTFS Format Specification version 2.4.0.
3a5b LTFS14104I Launched by "ltfs -o device_list".
3a5b LTFS14105I This binary is built for Linux (x86_64).
3a5b LTFS14106I GCC version is 7.4.0.
3a5b LTFS17087I Kernel version: Linux version 4.15.0-88-generic (buildd@lgw01-amd64-036) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 i386.
3a5b LTFS17089I Distribution: NAME="Ubuntu".
3a5b LTFS17089I Distribution: DISTRIB_ID=Ubuntu.
3a5b LTFS17085I Plugin: Loading "sg" tape backend.
Tape Device list:.
Device Name = /dev/sg1 (1.0.1.0), Vendor ID = QUANTUM , Product ID = ULTRIUM-HH8     , Serial Number = 1097001727, Product Name =[ULTRIUM-HH8].

**Comment by piste-jp-ibm** [comment]
`Vendor ID = QUANTUM` is the root cause. At this time, we only supports "IBM" drives officially.

Please read through issue #184 and other issues refereed from #184.

**Comment by ss4858** [comment]
Thanks for the information, that was quite helpful.
