### ISSUE TITLE
A low level tool to capture indexes on a tape 

### ISSUE THREAD

**Issue by piste-jp-ibm** [LinearTapeFileSystem/ltfs#196]
**Background**

Sometimes we got a problem related into dirty index. But we don't have any effective way to capture it. Because current code can capture a good index after the code did parse it.

**Describe the solution you'd like**

I would like to have a tool to capture indexes in low level (without any XML check at all)

**Describe alternatives you've considered**

Or it is helpful if LTFS can capture BAD index on-the-fly as special name for FA.

**Comment by greengreengreengit** [comment]
We have seen a few issues when mounting fails due to the XML parser failing. So access to the stored indexes would be useful for troubleshooting.

Because LTFS may not mount the tape, I think it has to be a standalone command line tool. This would run on an unmounted tape.

Thanks,

Martin

**Comment by mrichmon** [comment]
The tool `ltfsck` may help with the `--capture-index` option.

**Comment by piste-jp-ibm** [comment]
Yes. 

In most of cases, `--capture-index` option helps us. But `ltfsck` cannot capture indexes when the index is not parseable by the index parser of libltfs.

I would like to propose a tool to capture without checking index on tape at all. This tool might help us to debug **dirty** LTFS tape because of our index generator bug or LTFS tape creted by another implementation.

Of cause, we could add this kind of feature into `ltfs` also.

**Comment by greengreengreengit** [comment]
Indeed in these cases we had already used ltfsck, but it failed because of parsing.

However I think it makes sense to build this new function into ltfsck as it is a repair / rollback utility rather than putting it into ltfs.
Of course a new standalone tool would also work.
Have an option like —capture-raw-index that will just read indexes without parsing. Also need to choose which index you read from partition a or b.

Also how about adding a option to parse an eternal index from a file ? This would be great for testing.
So you could capture and save a bad index. Then work on the parser and test it without needing to use a tape?

Martin

**Comment by piste-jp-ibm** [comment]
Thank you for your suggestion @greengreengreengit.

It looks good to me. In my sense, it is good strategy to add a new tool which has following features. What do you think?
 - Capture index without parsing
 - Check captured index file 

The external behavior would be 
```
NAME
       ltfsindextool - Index debug tool for LTFS 

SYNOPSIS
       ltfsindextool  [  -e backend ]  [ -d devname ] [-p ip|dp] filename

       On Linux, device_name is like '/dev/IBMtape0', on OSX, device_name is like '0'(default: )

DESCRIPTION
       ltfsindextool is a program to debug on dirty LTFS index on tape

Available options are:
  -e, --backend=<name>      Use the specified tape device backend (default: sg)
  -d, --device=<name>       Tape device (Capture index to specified file when this option is specified. Otherwise run check process with specified file)
  -p, --partition=<name>    Specify a partition to capture index (effective only -d is specified)
  -h, --help                This help
```

**Comment by greengreengreengit** [comment]
Looks good !

**Comment by piste-jp-ibm** [comment]
@greengreengreengit ,

It takes a long time but I have merged the low level index tool now. Please try it if you still have an interest.

**Comment by Nooby1** [comment]
What would be the best tool to dump an index of a tapes contents for putting into a database? ltfsck? this new tool? Some other method?
