### ISSUE TITLE
lfts_ordered_copy xattr version on debian repos not matching?

### ISSUE THREAD

**Issue by andi-at-1** [LinearTapeFileSystem/ltfs#203]
I´ve tried yesterday the ltfs_ordered_copy script, first question, what is it good for? Sorting the files from small to big?

I got at first the error xattr not intsalled - so apt install python-xattr - installed version 0.9.6-1

then it startet, but produced an error telling me some methodwas not found. After a search i found out that at least the debian version of xattr has renamed the functions to getxattr(), setxattr(), listxattr(), no matter if using python2 or 3 version. The available methods are listed here:
```
attr.
xattr.XATTR_CREATE             xattr.getxattr(
xattr.XATTR_FINDERINFO_NAME    xattr.integer_types
xattr.XATTR_MAXNAMELEN         xattr.lib
xattr.XATTR_NOFOLLOW           xattr.listxattr(
xattr.XATTR_NOSECURITY         xattr.removexattr(
xattr.XATTR_REPLACE            xattr.setxattr(
xattr.XATTR_RESOURCEFORK_NAME  xattr.xattr(
xattr.compat 
```
After renaming all the method the script run, but produced some errors:
Failed to copy <verylongpath>NOTUSED_270317.sql.gz to <evenlongerpath>NOTUSED_270317.sql.gz: $[Errno 22] invalid mode ('wb') or filename: <youknowthepath>_NOTUSED_270317.sql.gz'

also it throws errors on copying some "thumbs.db" from windows preview, its getting confused and says "not a directory"
```
Failed to copy pathpathpath/Thumbs.db: $[Errno 20] Not a directory: '/pathpathpath/Thumbs.db/Thumbs.db'
Failed to copy pathpathpath/Thumbs.db: $[Errno 20] Not a directory: 'pathpathpath/Thumbs.db/Thumbs.db'
```

I think thats due to the wrong xattr version? Which one to use?

**Comment by piste-jp-ibm** [comment]
For first question, I can't get your point. Do you saying when you copy the files from disk to tape? 

----
For `pyxattr` thing
* On my RHEL7 env, it is `pyxattr-0.5.1-5.el7.x86_64` installed by yum
* On my MacOS env, it is `/usr/local/lib/python2.7/site-packages (0.6.1)` installed by pip2.7

----
For error message thing, the message after `Failed to copy pathpathpath/Thumbs.db:` is the description of exception created by python. I can't have any plan to improve at this time.
