### ISSUE TITLE
ltfs_ordered_copy: partially copy a dir while preserving hierarchy

### ISSUE THREAD

**Issue by softloft38p-michael** [LinearTapeFileSystem/ltfs#234]
We sometimes have files in a folder on a tape which we want to copy without copying the whole folder, but while keeping the existing hierarchy at the destination: what's the right set of params to use? 

Say I have the following files:
```
/mnt/tape/foo
- /bar
  - 1.txt
  - 2.txt
  - 3.txt
- /baz
  - 4.txt 
```
And want to copy only:
['/mnt/tape/foo/bar/1.txt', '/mnt/tape/foo/bar/2.txt', '/mnt/tape/foo/bar/4.txt']

To the destination `/home/usr/copy` such that the result is:

```
/home/usr/copy/foo
- /bar
  - 1.txt
  - 2.txt
- /baz
  - 4.txt
```

In my testing, if I run something like:
```
ltfs_ordered_copy '/mnt/tape/foo/bar/1.txt' '/mnt/tape/foo/bar/2.txt' '/mnt/tape/foo/bar/4.txt' -t /home/usr/copy
```

All the files end up in `/home/usr/copy` without the directories foo/bar or foo/baz.

**Comment by piste2750** [comment]
I think the behavior of the `ltfs_ordered_copy` is very similar to GNU's `cp`. So it is quite natural that you reported. 

I believe it is not easy to copy some of files under the tree with keeping the structure of tree by `cp` command also.

I think you have 2 options.

1. Copy entire tree with `-r` option and then remove unnecessary files
2. Copy the files with file list with using `--keep_tree` line `find /mnt/tape/foo -type f | grep -v 3.txt'' | ltfs_ordered_copy -t /home/usr/copy/foo --keep-tree=/mnt/tape/foo`

You can see various examples on the [wiki](https://github.com/LinearTapeFileSystem/ltfs/wiki/ltfs_ordered_copy).

**Comment by softloft38p-michael** [comment]
Thanks, `--keep-tree` was indeed what I needed.
