### ISSUE TITLE
LTFS Ordered Copy Errno 95

### ISSUE THREAD

**Issue by softloft38p-michael** [LinearTapeFileSystem/ltfs#236]
Trying to run ltfs_ordered_copy on an automounted SAN is returning `Check destination (I/O):[Errno 95] Operation not supported`. If I add an additional check on line 365:
```py
except IOError as e:
    if e.errno != 61 and e.errno != 93 and e.errno != 95: # Not ENODATA, ENOATTR
...
```
The copy works as expected. Is it safe to presume that if the operation is not supported the destination is not LTFS or is there another way that this can be handled? In this case, the destination is known not to be LTFS so it works, but it would be good to understand cases where this could be a problem and see if there is a way to allow the copy to proceed even if this cannot be determined programmatically with a flag or something.

Please let me know if there's any data I can provide that would help.

**Comment by piste-jp-ibm** [comment]
It looks `errno==95` is not supported error.
```C
#define	EOPNOTSUPP	95
```
Your destination filesystem seems not to support extended attribute `xattr` feature. 

So I think your fix is reasonable. But it looks good to forcibly  unset `-p` option when `errno==95` because `copy2()` might fail.
