### ISSUE TITLE
modprobe.d setup

### ISSUE THREAD

**Issue by softloft38p-michael** [LinearTapeFileSystem/ltfs#249]
I have the following in `/etc/modprobe.d/sg.conf` on Centos7:

```
options sg def_reserved_size=1048576
```

But when I run `cat /proc/scsi/sg/debug` it shows:
```max_active_device=549  def_reserved_size=32768```

How do I get these settings to take effect?

**Comment by piste-jp-ibm** [comment]
Reloading of the driver is required. Did you reboot the machine after creating the file?

I believe you can't reload the sg driver on-the-fly because the disk driver would use it already.

**Comment by softloft38p-michael** [comment]
Rebooting did apply the new settings. Thanks! I'll submit a PR with notes in the README to help others.
