### ISSUE TITLE
Reading more MAM fields from mounted tape

### ISSUE THREAD

**Issue by greengreengreengit** [LinearTapeFileSystem/ltfs#256]
Currently we read MAM medium metadata using SCSI commands whilst the tape is unmounted. However if the tape is already mounted then we cannot read them. The manufacturers serial number is very useful for tape identification.

It would be great if 0x0400, 0x0401, 0x405 and 0x0406 could be added as Virtual extended attributes ltfs.mediaManufacturer, ltfs.mediaSerialNumber, ltfs.mediaDensityCode and ltfs.mediaManufactureDate.
These parameters don't change so could be read just once and stored internally.

**Comment by greengreengreengit** [comment]
I see the new EA for log sense, which is great !

Instead of the above MAM EA, could have a low level command for READ ATTRIBUTE using an EA like ltfs.vendor.IBM.readAttribute.XXXX.YYYY.

Where XXXX is first sense code and YoYotta is length. So for example ltfs.vendor.IBM.readAttribute.0400.0100. This would send Read Attribute starting from 0x0400 with a length of 256 bytes.

**Comment by piste-jp-ibm** [comment]
> Instead of the above MAM EA, could have a low level command for READ ATTRIBUTE using an EA like ltfs.vendor.IBM.readAttribute.XXXX.YYYY.

It is easy to implement this. I will do this within a few days. But the MAM length is not so long, 1088 bytes.

It will return everything via VEA `ltfs.vendor.IBM.readAttribute`

**Comment by piste-jp-ibm** [comment]
> It will return everything via VEA `ltfs.vendor.IBM.readAttribute`

I realized the description is wrong... The drive can return different MAM values by partition. So `ltfs.vendor.IBM.mediaMAM.XX` would be good.

XX shall be a partition, `IP` or `DP`.
