### ISSUE TITLE
Support for another Quantum LTO-6 drive

### ISSUE THREAD

**Issue by greengreengreengit** [LinearTapeFileSystem/ltfs#257]
I have been testing with Quantum LTO drives. The LTO-5 drives are working well since the recent multi vendor changes.

There are also Quantum DRIVE_LTO6_HH drives that return "ULTRIUM 6".
They behave like the "ULTRIUM 5" ones.

Both these drives support page 0x31, so no need to switch to page 0x17 like the HP drives.

So I think the only change is adding "ULTRIUM 6" to quantum_supported_drives in quantum_tape.c ?

**Comment by piste-jp-ibm** [comment]
> So I think the only change is adding "ULTRIUM 6" to quantum_supported_drives in quantum_tape.c ?

Yes. I agree.
