### ISSUE TITLE
Configure problem in Manjaro Linux (v2.4-stable branch)

### ISSUE THREAD

**Issue by sardaukar** [LinearTapeFileSystem/ltfs#262]
**Describe the bug**
Cannot run `./autogen.sh`

**To Reproduce**
1. clone repo
2. run `./autogen.sh`

**Expected behavior**
Autogen runs successfully

**Screenshots**

```
configure.ac:43: error: AC_CONFIG_MACRO_DIR can only be used once
./lib/autoconf/general.m4:1970: AC_CONFIG_MACRO_DIR is expanded from...
configure.ac:43: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: autom4te failed with exit status: 1
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: linking file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:43: error: AC_CONFIG_MACRO_DIR can only be used once
./lib/autoconf/general.m4:1970: AC_CONFIG_MACRO_DIR is expanded from...
configure.ac:43: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
configure.ac:43: error: AC_CONFIG_MACRO_DIR can only be used once
./lib/autoconf/general.m4:1970: AC_CONFIG_MACRO_DIR is expanded from...
configure.ac:43: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
autoheader: error: '/usr/bin/autom4te' failed with exit status: 1
configure.ac:43: error: AC_CONFIG_MACRO_DIR can only be used once
./lib/autoconf/general.m4:1970: AC_CONFIG_MACRO_DIR is expanded from...
configure.ac:43: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
automake: error: autoconf failed with exit status: 1
```

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 20.1

**Additional context**

autoconf 2.71-1
automake 1.16.3-1
m4 1.4.18-3
libtool 2.4.6+42+gb88cebd5-14

**Comment by piste-jp-ibm** [comment]
Please try to remove the line below, but I'm not sure this works fine on other systems correctly. So I hesitate to remove the line at this time.

https://github.com/LinearTapeFileSystem/ltfs/blob/16a08be53dce3807aac6094e7295744f8f617d35/configure.ac#L43

**Comment by sardaukar** [comment]
Thanks, I could `autogen` and `configure` with that line removed! I also had to comment out

```
#include <sys/sysctl.h>
```
in `src/libltfs/arch/arch_info.c` since sysctl this has been deprecated since Linux 5.5 and I'm running 5.11

**Comment by xosevp** [comment]
> Thanks, I could `autogen` and `configure` with that line removed! I also had to comment out
> 
> ```
> #include <sys/sysctl.h>
> ```
> 
> in `src/libltfs/arch/arch_info.c` since sysctl this has been deprecated since Linux 5.5 and I'm running 5.11

It was removed in Glibc 2.32: https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=076f09afbac1aa57756faa7a8feadb7936a724e4
And Linux kernel 5.5: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=61a47c1ad3a4dc6882f01ebdc88138ac62d0df03
