### ISSUE TITLE
bad defined QUANTUM device

### ISSUE THREAD

**Issue by xosevp** [LinearTapeFileSystem/ltfs#265]
At 
https://github.com/LinearTapeFileSystem/ltfs/blob/53a940605970711697faa34d46751016b97311f4/src/tape_drivers/quantum_tape.c#L71

It is identified as as DRIVE_LTO**5**_HH instead of DRIVE_LTO**6**_HH

And in the LTFS from Quantum, based on IBM 2.4.0.2 code, they are defined as:
```
DRIVE_QTM5        = 0xA105, /* QUANTUM Gen 5 */
DRIVE_QTM6        = 0xA106, /* QUANTUM Gen 6 */
```
Code from: https://forensics.cert.org/centos/cert/8/SRPMS/qtmltfs-2.4.0.2-1.el8.src.rpm
to extract it: rpm2cpio qtmltfs-2.4.0.2-1.el8.src.rpm | cpio -i -d

hint: look for "QUANTUM_BUILD" in the code.

**Comment by piste-jp-ibm** [comment]
Oops, this is a bug.
