### ISSUE TITLE
ltfs_ordered_copy python3

### ISSUE THREAD

**Issue by svein** [LinearTapeFileSystem/ltfs#273]
I compiled latest ltfs from git master to run on rhel8. My first problem running ltfs_ordered_copy was that env python don't exist on rhel8 anymore, so I tried changing it to python3. This gave me the error:
`Traceback (most recent call last):
  File "/opt/ltfs-git/bin/ltfs_ordered_copy", line 447, in <module>
    partation_list = sorted(tape.keys())
TypeError: '<' not supported between instances of 'str' and 'bytes'`

I suspect it's because ltfs_ordered_copy is not python3 ready. I tried to install python2, but it seems python2-pyxattr is locked away in the openstack-15-for-rhel-8-x86_64-rpms repo. Of cause I can get the package from CentOS, but it seems to be not a great solution. 

Is python3 support considered for ltfs_ordered_copy? python2 has been EOL for over a year now, so it will be more and more difficult to find it on newer distros going forward.

**Comment by piste-jp-ibm** [comment]
For the first problem, you can use the tips here.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-python3_configuring-basic-system-settings#configuring-the-unversioned-python_installing-and-using-python

**Comment by piste-jp-ibm** [comment]
The exception problem looks a bug of `ltfs_ordered_copy`.

I wrote it to support both python2 and python3. And it can start correctly and then stop because of unhandled exception.

**Comment by svein** [comment]
> For the first problem, you can use the tips here.
> 
> https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-python3_configuring-basic-system-settings#configuring-the-unversioned-python_installing-and-using-python

Thanks.

Yes it seems to be a bug then. There isn't much other output.
```
 /opt/ltfs-git/bin/ltfs_ordered_copy -r -v /mnt/ltfs2/ /dest/
Tape order aware copy for LTFS
Destination /dest/ is not LTFS
...
...
On disk sources: 0
Source tapes: 1
Traceback (most recent call last):
  File "/opt/ltfs-git/bin/ltfs_ordered_copy", line 447, in <module>
    partation_list = sorted(tape.keys())
TypeError: '<' not supported between instances of 'str' and 'bytes'
```
A couple of warning about null byte files, but that is as expected and not relevant to this bug I think. I see it regularly on rhel7
`Failed to get attribute of "/mnt/ltfs2/somepath/somefile.log": [Errno 61] No data available`

**Comment by piste-jp-ibm** [comment]
It looks a bug when 0-byte file exists.

Only non-0-byte files
```
#~piste/ltfs-oss/bin/ltfs_ordered_copy ./mnt/* .
Tape order aware copy for LTFS
Destination . is not LTFS
On disk sources: 0
Source tapes: 1
Processing tape b'c1e75b5f-7344-440e-970b-333172f7f069', Partition b'b'
Sorting 4 files on b'c1e75b5f-7344-440e-970b-333172f7f069' (b'b')
Copying files on b'c1e75b5f-7344-440e-970b-333172f7f069' (b'b')
File copy from tape is on going: 4/4
Copied 4 files.
```

With a 0-byte file
```
# touch ./mnt/zzz
#~piste/ltfs-oss/bin/ltfs_ordered_copy ./mnt/* .
Tape order aware copy for LTFS
Destination . is not LTFS
Failed to get attribute of "./mnt/zzz": [Errno 61] No data available
On disk sources: 0
Source tapes: 1
Traceback (most recent call last):
  File "/home/piste/ltfs-oss/bin/ltfs_ordered_copy", line 447, in <module>
    partation_list = sorted(tape.keys())
TypeError: '<' not supported between instances of 'str' and 'bytes'
```

**Comment by piste-jp-ibm** [comment]
Please use the patch below. I will integrate the fix later.

```patch
diff --git a/src/utils/ltfs_ordered_copy b/src/utils/ltfs_ordered_copy
index 10f14db..a018ee5 100755
--- a/src/utils/ltfs_ordered_copy
+++ b/src/utils/ltfs_ordered_copy
@@ -72,6 +72,8 @@ class CopyItem:
             self.size  = os.path.getsize(self.src)
         except Exception as e:
             self.logger.error('Failed to get attribute of "{0}": {1}'.format(self.src, str(str(e))))
+            self.part = b'a'
+            self.start = 0

         return (self.vuuid, self.part, self.start)
```

**Comment by svein** [comment]
The patch did the trick. Thank you

**Comment by piste-jp-ibm** [comment]
I confirmed my patch works for both python3.9 and python2.7 on Mac.
