### ISSUE TITLE
Need to support `ltfs.hash.*` extended attributes

### ISSUE THREAD

**Issue by ljnash** [LinearTapeFileSystem/ltfs#297]
I've been trying to write extended attributes (EA) to files stored on an LTO-5 tape but have been prevented from writing EAs that begin with `user.ltfs.*`.  This seems like it may be a bug so I wanted to highlight the issue and seek advice/feedback.

IBM's documentation (https://www.ibm.com/docs/en/spectrum-archive-sde/2.4.1.0?topic=tips-extended-attributes) on this subject is slightly confusing and seems to imply that Linux systems would save `user.*` attributes and yet as I will show later, the schema doesn't show `user.*` EAs.  It seems that Linux is unusual in already having defined prefix's for file EAs, unlike Windows and Mac OSX.  On a Linux file system a user is only permitted to write an EA that begins with `user.*`.  As an example the attribute `ltfs.hash.md5sum` on Windows and Mac is written as `user.ltfs.hash.md5sum` under Linux. An SNIA LTFS Format Specification document (https://www.snia.org/sites/default/files/technical_work/LTFS/LTFS_Format_2.4.0_TechPosition.pdf) mentions on page 83 that hash values may be stored in the form of `ltfs.hash.<hashtype>` as an LTFS extended attribute.

After some experimentation it seems that the current ltfs implementation here prevents any EA that begins `user.ltfs` from being written to a file stored on an LTFS volume.  Consider the following examples:
```
$ setfattr -n user.ltfs.hash.md5sum -v dbb78ccc96d658b5a00ebbe543a9706e /mnt/ltfs/python/md5sum.py
setfattr: /mnt/ltfs/python/md5sum.py: Permission denied

$ setfattr -n ltfs.hash.md5sum -v dbb78ccc96d658b5a00ebbe543a9706e /mnt/ltfs/python/md5sum.py 
setfattr: /mnt/ltfs/python/md5sum.py: Operation not supported

$ xattr -w user.ltfs.hash.md5sum dbb78ccc96d658b5a00ebbe543a9706e /mnt/ltfs/python/md5sum.py
[Errno 13] Permission denied: b'/mnt/ltfs/python/md5sum.py'
```
and yet the following is fine
```
$ xattr -w user.rabbit.hash.md5sum dbb78ccc96d658b5a00ebbe543a9706e /mnt/ltfs/python/md5sum.py
$ xattr -p user.rabbit.hash.md5sum /mnt/ltfs/python/md5sum.py
dbb78ccc96d658b5a00ebbe543a9706e
```
and for files not stored on an ltfs volume
```
$ xattr -w user.ltfs.hash.md5sum dbb78ccc96d658b5a00ebbe543a9706e /home/lee/Documents/md5sum.py
$ xattr /home/lee/Documents/md5sum.py
user.ltfs.hash.md5sum
$ xattr -p user.ltfs.hash.md5sum /home/lee/Documents/md5sum.py
dbb78ccc96d658b5a00ebbe543a9706e
$ getfattr -d /home/lee/Documents/md5sum.py
getfattr: Removing leading '/' from absolute path names
# file: home/lee/Documents/md5sum.py
user.ltfs.hash.md5sum="dbb78ccc96d658b5a00ebbe543a9706e"
```
One oddity I've found using Debian is that the attr package (which also provides getfattr and setfattr) doesn't report the user prefix (even though getfattr does), which confused me to begin with so I thought it worth pointing out.
```
$ attr -l /mnt/ltfs/python/md5sum.py
Attribute "rabbit.hash.md5sum" has a 32 byte value for /mnt/ltfs/python/md5sum.py
```
An extract from the tape schema recorded following unmounting of the tape is shown below and demonstrates that the EAs are reported without the leading `user.*` prefix which is what I'd expected for cross platform compatibility.
```
<ltfsindex version="2.4.0">
<creator>IBM LTFS 2.4.3.2 (Prelim) - Linux - ltfs - Unmount</creator>
...
<file>
<name>md5sum.py</name>
<length>4608</length>
<readonly>false</readonly>
<creationtime>2021-06-20T14:54:07.289473210Z</creationtime>
<changetime>2021-06-21T19:23:49.361383276Z</changetime>
<modifytime>2021-06-13T15:13:35.247889000Z</modifytime>
<accesstime>2021-06-21T19:14:16.846963870Z</accesstime>
<backuptime>2021-06-20T14:54:07.289473210Z</backuptime>
<fileuid>4</fileuid>
<extendedattributes>
<xattr>
<key>rabbit.hash.md5sum</key>
<value>dbb78ccc96d658b5a00ebbe543a9706e</value>
</xattr>
<xattr>
<key>squirrel.hash.md5sum</key>
<value>dbb78ccc96d658b5a00ebbe543a9706e</value>
</xattr>
</extendedattributes>
<extentinfo>
<extent>
<fileoffset>0</fileoffset>
<partition>b</partition>
<startblock>8</startblock>
<byteoffset>0</byteoffset>
<bytecount>4608</bytecount>
</extent>
</extentinfo>
</file>
```

For reference, the tape was formatted and had data written to it using "LTFS version 2.4.3.2 (Prelim)", the latest stable-2.4 build downloaded and compiled 2 weeks ago. The OS used is Debian 10 (Buster) on an Intel x64 platform using an HP LTO-5 Ultrium 3000 tape drive in an external SAS enclosure and an HP SAS9205-4i4e HBA.

**Comment by piste-jp-ibm** [comment]
At this time,  EAs for hash value is not implemented at all. So LTFS rejects the request against `user.ltfs.hash.foo` (in Linux) because under `user.ltfs` is reserved area.

From the format point of view, they are optional (See F.3.1 in the LTFS Spec 2.4). So it is not a violation. But it is good to support in the near future.
