### ISSUE TITLE
Compile error on freebsd 12.2 on latest git pull.

### ISSUE THREAD

**Issue by ia2115** [LinearTapeFileSystem/ltfs#322]
i have all the Prerequisites as stated on ltfs page, i build and install like the list on page and get this:

see full run here: https://paste.sh/Hpr5W9zo#8_2dp1_bGaVBxMDP1aQO61pN
autogen
configure
make -> error down here.

Need recommandation on how to proceed to make this work? any hints.

```
~/ltfs # make
make  all-recursive
Making all in messages
Making all in src
Making all in libltfs
Making all in tape_drivers/generic/file
Making all in tape_drivers/generic/itdtimg
Making all in tape_drivers/freebsd/cam
/bin/sh ../../../../libtool  --tag=CC --tag=disable-static  --mode=compile cc -DHAVE_CONFIG_H -I. -I../../../..  -D_GNU_SOURCE -I../../../../src -DLTFS_CONFIG_FILE='"/usr/local/etc/ltfs.conf"' -DLTFS_BASE_DIR='"/usr/local"' -DUSE_NEW_LOCKING -I ../../.. -I ../..  -Wall -Wsign-compare -fsigned-char -I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64 -I/usr/local/include/uuid -I/usr/local/include -I/usr/local/include/libxml2 -DU_DISABLE_RENAMING=1 -I/usr/local/include -D ENABLE_SNMP -O2 -pipe -I/usr/local/include -I/include -fstack-protector-strong -fno-strict-aliasing -std=c99 -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -O2 -pipe -I/usr/local/include -I/include -fstack-protector-strong -fno-strict-aliasing -std=c99 -Ufreebsd12 -Dfreebsd12=freebsd12 -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DUSE_THREAD_SAFE_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -I/usr/local/lib/perl5/5.32/mach/CORE -I/usr/include -I. -I/usr/local/include -g -O2 -D_FORTIFY_SOURCE=0 -O0 -ggdb -MT libtape_cam_la-cam_tc.lo -MD -MP -MF .deps/libtape_cam_la-cam_tc.Tpo -c -o libtape_cam_la-cam_tc.lo `test -f 'cam_tc.c' || echo './'`cam_tc.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../../.. -D_GNU_SOURCE -I../../../../src -DLTFS_CONFIG_FILE=\"/usr/local/etc/ltfs.conf\" -DLTFS_BASE_DIR=\"/usr/local\" -DUSE_NEW_LOCKING -I ../../.. -I ../.. -Wall -Wsign-compare -fsigned-char -I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64 -I/usr/local/include/uuid -I/usr/local/include -I/usr/local/include/libxml2 -DU_DISABLE_RENAMING=1 -I/usr/local/include -D ENABLE_SNMP -O2 -pipe -I/usr/local/include -I/include -fstack-protector-strong -fno-strict-aliasing -std=c99 -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -O2 -pipe -I/usr/local/include -I/include -fstack-protector-strong -fno-strict-aliasing -std=c99 -Ufreebsd12 -Dfreebsd12=freebsd12 -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DUSE_THREAD_SAFE_LOCALE -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -I/usr/local/lib/perl5/5.32/mach/CORE -I/usr/include -I. -I/usr/local/include -g -O2 -D_FORTIFY_SOURCE=0 -O0 -ggdb -MT libtape_cam_la-cam_tc.lo -MD -MP -MF .deps/libtape_cam_la-cam_tc.Tpo -c cam_tc.c  -fPIC -DPIC -o .libs/libtape_cam_la-cam_tc.o
cam_tc.c:286:4: error: use of undeclared identifier 'priv'
                        priv->vendor = (*cur)->vendor_type;
                        ^
1 error generated.
*** Error code 1

Stop.
make[3]: stopped in /root/ltfs/src/tape_drivers/freebsd/cam
*** Error code 1
*** Error code 1
*** Error code 1
```

**Comment by piste-jp-ibm** [comment]
Pease try the patch below.

Modify line 286 in src/tape_drivers/freebsd/cam/cam_tc.c

from 

```C
priv->vendor = (*cur)->vendor_type;
```

to 

```C
softc->vendor = (*cur)->vendor_type;
```

**Comment by ia2115** [comment]
that worked, after make uninstall/ make clean i recompiled it.. and no errors.

now to turn on lto and try it out.
# ltfs
LTFS9015W Setting the locale to 'en_US.UTF-8'. If this is wrong, please set the LANG environment variable before starting ltfs.
18e88 LTFS14000I LTFS starting, LTFS version 2.5.0.0 (Prelim), log level 2.
18e88 LTFS14058I LTFS Format Specification version 2.4.0.
18e88 LTFS14104I Launched by "ltfs".
18e88 LTFS14105I This binary is built for FreeBSD.
18e88 LTFS14106I GCC version is FreeBSD Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2).
18e88 LTFS17087I Kernel version: FreeBSD 12.2-STABLE r369131 GENERIC
.
18e88 LTFS14063I Sync type is "time", Sync time is 300 sec.
18e88 LTFS17085I Plugin: Loading "cam" tape backend.
18e88 LTFS17085I Plugin: Loading "unified" iosched backend.
18e88 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
18e88 LTFS31223I Opening a device through CAM driver (/dev/sa0)
18e88 LTFS31225I Cannot open device '/dev/sa0' (2)
18e88 LTFS12012E Cannot open device: failed backend open call.
18e88 LTFS10004E Cannot open device '/dev/sa0'.

**Comment by ia2115** [comment]
# ltfs -o device_list
LTFS9015W Setting the locale to 'en_US.UTF-8'. If this is wrong, please set the LANG environment variable before starting ltfs.
18da3 LTFS14000I LTFS starting, LTFS version 2.5.0.0 (Prelim), log level 2.
18da3 LTFS14058I LTFS Format Specification version 2.4.0.
18da3 LTFS14104I Launched by "ltfs -o device_list".
18da3 LTFS14105I This binary is built for FreeBSD.
18da3 LTFS14106I GCC version is FreeBSD Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2).
18da3 LTFS17087I Kernel version: FreeBSD 12.2-STABLE r369131 GENERIC
.
18da3 LTFS17085I Plugin: Loading "cam" tape backend.
Tape Device list:.

whonder why it cant find and display it.


from freebsd 12.2 /var/log/messages:

Dec 13 14:31:08 jails kernel: sa0 at mps0 bus 0 scbus0 target 83 lun 0
Dec 13 14:31:08 jails kernel: sa0: <TANDBERG LTO-6 HH 3579> Removable Sequential Access SPC-4 SCSI device
Dec 13 14:31:08 jails kernel: sa0: Serial Number HUJ527449P
Dec 13 14:31:08 jails kernel: sa0: 600.000MB/s transfers
Dec 13 14:31:08 jails kernel: sa0: Command Queueing enabled

**Comment by ia2115** [comment]
# ltfs -o devname=/dev/sa0
LTFS9015W Setting the locale to 'en_US.UTF-8'. If this is wrong, please set the LANG environment variable before starting ltfs.
18daf LTFS14000I LTFS starting, LTFS version 2.5.0.0 (Prelim), log level 2.
18daf LTFS14058I LTFS Format Specification version 2.4.0.
18daf LTFS14104I Launched by "ltfs -o devname=/dev/sa0".
18daf LTFS14105I This binary is built for FreeBSD.
18daf LTFS14106I GCC version is FreeBSD Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2).
18daf LTFS17087I Kernel version: FreeBSD 12.2-STABLE r369131 GENERIC
.
18daf LTFS14063I Sync type is "time", Sync time is 300 sec.
18daf LTFS17085I Plugin: Loading "cam" tape backend.
18daf LTFS17085I Plugin: Loading "unified" iosched backend.
18daf LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
18daf LTFS31223I Opening a device through CAM driver (/dev/sa0)
18daf LTFS31228I Product ID is 'LTO-6 HH'
18daf LTFS31229I Vendor ID is TANDBERG
18daf LTFS31232I Firmware revision is 3579
18daf LTFS31233I Drive serial is HUJ527449P
18daf LTFS17160I Maximum device block size is 131072.
18daf LTFS11330I Loading cartridge.
18daf LTFS11332I Load successful.
18daf LTFS31213I Error on modeselect: (pass15:mps0:0:83:0): MODE SELECT(10). CDB: 55 00 00 00 00 00 00 00 30 00
(pass15:mps0:0:83:0): CAM status: SCSI Status Error
(pass15:mps0:0:83:0): SCSI status: Check Condition
(pass15:mps0:0:83:0): SCSI sense: ILLEGAL REQUEST asc:24,0 (Invalid field in CDB)
(pass15:mps0:0:83:0): Command byte 1 bit 4 is invalid
 (-20501) HUJ527449P
18daf LTFS17103E Cannot set PEWS: Mode Select for Device Configuration Extension failed (-20501).
18daf LTFS17157I Changing the drive setting to write-anywhere mode.
18daf LTFS11005I Mounting the volume.
18daf LTFS31214E Error on locate: msg = NULL (-20802) HUJ527449P
18daf LTFS12037E Cannot seek: backend call failed (-20802).
18daf LTFS11006E Cannot read volume: failed to load the tape.
18daf LTFS14013E Cannot mount the volume.
18daf LTFS31213I Error on modeselect: (pass15:mps0:0:83:0): MODE SELECT(10). CDB: 55 00 00 00 00 00 00 00 30 00
(pass15:mps0:0:83:0): CAM status: SCSI Status Error
(pass15:mps0:0:83:0): SCSI status: Check Condition
(pass15:mps0:0:83:0): SCSI sense: ILLEGAL REQUEST asc:24,0 (Invalid field in CDB)
(pass15:mps0:0:83:0): Command byte 1 bit 4 is invalid
 (-20501) HUJ527449P
18daf LTFS17155E Cannot set WRITE MODE: Mode Select for Device Configuration Extension failed (-20501).
18daf LTFS31213I Error on modesense: (pass15:mps0:0:83:0): MODE SENSE(10). CDB: 5a 00 24 00 00 00 00 00 28 00
(pass15:mps0:0:83:0): CAM status: SCSI Status Error
(pass15:mps0:0:83:0): SCSI status: Check Condition
(pass15:mps0:0:83:0): SCSI sense: ILLEGAL REQUEST asc:24,0 (Invalid field in CDB)
(pass15:mps0:0:83:0): Command byte 2 bit 5 is invalid
 (-20501) HUJ527449P

with a tape inserted

**Comment by ia2115** [comment]
when i try format det tape in drive:

# mkltfs -d /dev/sa0 -n test
LTFS9015W Setting the locale to 'en_US.UTF-8'. If this is wrong, please set the LANG environment variable before starting mkltfs.
LTFS15000I Starting mkltfs, LTFS version 2.5.0.0 (Prelim), log level 2.
LTFS15041I Launched by "mkltfs -d /dev/sa0 -n test".
LTFS15042I This binary is built for FreeBSD.
LTFS15043I GCC version is FreeBSD Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2).
LTFS17087I Kernel version: FreeBSD 12.2-STABLE r369131 GENERIC
.
LTFS15003I Formatting device '/dev/sa0'.
LTFS15004I LTFS volume blocksize: 524288.
LTFS15005I Index partition placement policy: None.

LTFS11337I Update index-dirty flag (1) - NO_BARCODE (0x0x802b1a000).
LTFS17085I Plugin: Loading "cam" tape backend.
LTFS31223I Opening a device through CAM driver (/dev/sa0)
LTFS31228I Product ID is 'LTO-6 HH'
LTFS31229I Vendor ID is TANDBERG
LTFS31232I Firmware revision is 3579
LTFS31233I Drive serial is HUJ527449P
LTFS17160I Maximum device block size is 131072.
LTFS11330I Loading cartridge.
LTFS11332I Load successful.
LTFS31213I Error on modeselect: (pass15:mps0:0:83:0): MODE SELECT(10). CDB: 55 00 00 00 00 00 00 00 30 00
(pass15:mps0:0:83:0): CAM status: SCSI Status Error
(pass15:mps0:0:83:0): SCSI status: Check Condition
(pass15:mps0:0:83:0): SCSI sense: ILLEGAL REQUEST asc:24,0 (Invalid field in CDB)
(pass15:mps0:0:83:0): Command byte 1 bit 4 is invalid
 (-20501) HUJ527449P
LTFS17103E Cannot set PEWS: Mode Select for Device Configuration Extension failed (-20501).
LTFS17157I Changing the drive setting to write-anywhere mode.
LTFS15049I Checking the medium (mount).
LTFS31214E Error on locate: msg = NULL (-20802) HUJ527449P
LTFS12037E Cannot seek: backend call failed (-20802).
LTFS11006E Cannot read volume: failed to load the tape.
LTFS31213I Error on modeselect: (pass15:mps0:0:83:0): MODE SELECT(10). CDB: 55 00 00 00 00 00 00 00 30 00
(pass15:mps0:0:83:0): CAM status: SCSI Status Error
(pass15:mps0:0:83:0): SCSI status: Check Condition
(pass15:mps0:0:83:0): SCSI sense: ILLEGAL REQUEST asc:24,0 (Invalid field in CDB)
(pass15:mps0:0:83:0): Command byte 1 bit 4 is invalid
 (-20501) HUJ527449P
LTFS17155E Cannot set WRITE MODE: Mode Select for Device Configuration Extension failed (-20501).
LTFS31213I Error on modesense: (pass15:mps0:0:83:0): MODE SENSE(10). CDB: 5a 00 24 00 00 00 00 00 28 00
(pass15:mps0:0:83:0): CAM status: SCSI Status Error
(pass15:mps0:0:83:0): SCSI status: Check Condition
(pass15:mps0:0:83:0): SCSI sense: ILLEGAL REQUEST asc:24,0 (Invalid field in CDB)
(pass15:mps0:0:83:0): Command byte 2 bit 5 is invalid
 (-20501) HUJ527449P
LTFS15023I Formatting failed.

**Comment by piste2750** [comment]
Build break was fixed.

Other descriptions imply the cam driver doesn't support `TANDBERG` drive. It would be dup of #286.

**Comment by piste2750** [comment]
For https://github.com/LinearTapeFileSystem/ltfs/issues/322#issuecomment-992507880, `mkltfs` received a seek error from the drive (EOD not found) while checking the tape is formatted or not.

I believe someone down the power of a drive that has this tape before. Please try `mkltfs -f` instead if it is sure you can erase the current contents on the tape. `-f` option of `mkltfs` skips the format check before actual format.

```
LTFS15049I Checking the medium (mount).
LTFS31214E Error on locate: msg = NULL (-20802) HUJ527449P
LTFS12037E Cannot seek: backend call failed (-20802).
LTFS11006E Cannot read volume: failed to load the tape.
```

```
#define EDEV_EOD_NOT_FOUND           20802  /* 08/1403 EOD not found */
```
