### ISSUE TITLE
Question about support for SimplyPro LTO-9 single unit

### ISSUE THREAD

**Issue by DavidValin** [LinearTapeFileSystem/ltfs#359]
Hello

I am new to LTO and LTFS world, so forgive my ignorance. I am trying to evaluate using LTO tapes (LTFS) and found a nice tape drive for LTO-9 but I am not sure if its supported with this toolkit. https://tapes.nl/product/symplypro-lto-desktop-thunderbolt-3-hh-lto-9/

Isn't the api to talk with the tape drives the same for all of them?
Isn't LTFS a standard used across all devices?

If not, why wouldn't it be compatible with this drive for example?

I am just trying to use the LTFS filesystem with this unit in anything that is not Mac or Windows, no fancy stuff, just mount the tape as a drive, write and read from it

**Comment by piste-jp-ibm** [comment]
Your questions are not clear to me. May be, you and I am not in the same page. So I would like to start from the beginning.

First of all, you might not be able to see any changes in your system when you connect a LTO drive to your system except only one device is added into your system. (You can't see any drive icon on your desktop or somewhere.) 

Once you connected a LTO drive in your system, a device file `/dev/sg?` is added on your machine in Linux or device entry is added on the 'system report' in Mac. This "device" on the system shall be used from one of application for tape like `tar` command. (It is quite deferent from the disk...)

LTFS is one of software to use LTO drive on system. So LTFS requires target drive is detcted on the system before using it. This drive detection problem is not a scope of this LTFS project at all. It just use a tape device detected by the system.

> I am just trying to use the LTFS filesystem with this unit in anything that is not Mac or Windows, no fancy stuff, just mount the tape as a drive, write and read from it

LTFS is not a S/W that runs within a tape device at all. You need to connect the drive to the system (Linux or Mac) and run the LTFS S/W on that system. (For windows, the code in this project does not support it. Use other vendor's LTFS with supported drives.)

**Comment by DavidValin** [comment]
So is it correct to say that LTFS is a file system and this is standard in the market, and this "ltfs" project is a toolkit that implements the api to talk to this LTFS filesystem? Why does it state the tape drives supported in the README then? I dont understand....

So to use this specific drive I would need to find a specific driver for this specific drive in linux, and once I have the /dev/sg? device available this ltfs project is going to be able to format, read and write files as a "normal" folder in the mounted device using LTFS filesystem?

**Comment by DavidValin** [comment]
I really appreciate your time and answers. So what I understood is that in theory it should be detected but it has not been validates by your team.

Thanks a lot!!
