### ISSUE TITLE
how to release partition created by mkltfs?

### ISSUE THREAD

**Issue by 17701311118** [LinearTapeFileSystem/ltfs#363]
![image](https://user-images.githubusercontent.com/113981831/193524520-4961bc1b-5a76-469b-ba24-7be622317fd3.png)

**Comment by piste-jp-ibm** [comment]
Try `--wipe` option of the `mkltfs` command.

https://github.com/LinearTapeFileSystem/ltfs/wiki/mkltfs

**Comment by piste-jp-ibm** [comment]
Close because there is no response in 2 weeks.
