### ISSUE TITLE
ltfs_ordered_copy LTFS check error

### ISSUE THREAD

**Issue by jycm205** [LinearTapeFileSystem/ltfs#370]
When I try running `ltfs_ordered_copy` to copy files to an LTFS formatted tape I get the following error:
```
Check destination:startswith first arg must be bytes or a tuple of bytes, not str
```

Copying to non-LTFS locations seems to work as expected.

If I print the value that xattr returns from an LTFS tape I get `b'LTFS LE'`. Should xattr be returning a string here? When running just the code related to generating and checking `sig`, I don't get an error if I convert `sig` to a string before checking if it starts with "LTFS" or if I change `if sig.startswith("LTFS"):` to `if sig.startswith(b"LTFS"):`.

I'm running the 2.4.5.0 release version on Fedora 36.

**Comment by piste-jp-ibm** [comment]
Thank you for your info. I confirmed.
