### ISSUE TITLE
Umount is not synchronous

### ISSUE THREAD

**Issue by donmor** [LinearTapeFileSystem/ltfs#381]
**Describe the bug**
When a tape is mounted on somewhere like /mnt and `umount /mnt` is executed, it returns to shell immediately, leaving the busy /dev/st0 to the next command (in a script), which corrupts the tape and makes all data on it unrecoverable. Luckily I'm using a spare tape to test my script :-\

**To Reproduce**
1. make a script with this two lines: `umount /mnt` and `mt-st -f /dev/st0 eject`
2. run the script with sudo
The error message is `/dev/st0: Input/output error`. The next time the tape is loaded it produces `Failed to read label (-1012) from partition 1` and won't load

**Expected behavior**
The script get blocked at `umount` until the tape drive is ready, and the tape is ejected without error.

**Desktop:**
 - OS: Ubuntu 22.04
 - Version: HPE StoreOpen Software 3.4.0 (I wonder if the open source ltfs have the same issue)

**Comment by donmor** [comment]
Update: `ltfs -o devname=/dev/st0 -o release_device` seems to be safe. It needs to be in a loop until the /dev/st0 is accessible.

**Comment by piste-jp-ibm** [comment]
> When a tape is mounted on somewhere like /mnt and umount /mnt is executed, it returns to shell immediately, leaving the busy /dev/st0 to the next command (in a script), which corrupts the tape and makes all data on it unrecoverable. 
>
> Expected behavior
> The script get blocked at umount until the tape drive is ready, and the tape is ejected without error.

This is the design of FUSE, not LTFS's. We cannot do anything about this. Please check the `ltfs` process is finished by the command `pidof ltfs`.

**Comment by piste-jp-ibm** [comment]
You can see the discussion in #378.

**Comment by donmor** [comment]
Oh that sounds helpful. I'll try it out later.

**Comment by donmor** [comment]
maybe there could be a blcking `-o umoumt` option in ltfs command? when issued it calls umount and wait until the process done.
Or just make `-o release_device` do this when called with a volume mounted.

**Comment by piste-jp-ibm** [comment]
Close because no action over a month.
