### ISSUE TITLE
HP 6250 LTO6 vs newest git not detected (device_list) cam /scsi error) freebsd 12.2

### ISSUE THREAD

**Issue by ia2115** [LinearTapeFileSystem/ltfs#391]
```
# ltfs -o device_list
LTFS9015W Setting the locale to 'en_US.UTF-8'. If this is wrong, please set the LANG environment variable before starting ltfs.
18d16 LTFS14000I LTFS starting, LTFS version 2.5.0.0 (Prelim), log level 2.
18d16 LTFS14058I LTFS Format Specification version 2.4.0.
18d16 LTFS14104I Launched by "ltfs -o device_list".
18d16 LTFS14105I This binary is built for FreeBSD.
18d16 LTFS14106I GCC version is FreeBSD Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2).
18d16 LTFS17087I Kernel version: FreeBSD 12.2-STABLE r369131 GENERIC
.
18d16 LTFS17085I Plugin: Loading "cam" tape backend.
Tape Device list:.
```

```
# ltfs -o devname=/dev/sa0
LTFS9015W Setting the locale to 'en_US.UTF-8'. If this is wrong, please set the LANG environment variable before starting ltfs.
18e66 LTFS14000I LTFS starting, LTFS version 2.5.0.0 (Prelim), log level 2.
18e66 LTFS14058I LTFS Format Specification version 2.4.0.
18e66 LTFS14104I Launched by "ltfs -o devname=/dev/sa0".
18e66 LTFS14105I This binary is built for FreeBSD.
18e66 LTFS14106I GCC version is FreeBSD Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2).
18e66 LTFS17087I Kernel version: FreeBSD 12.2-STABLE r369131 GENERIC
.
18e66 LTFS14063I Sync type is "time", Sync time is 300 sec.
18e66 LTFS17085I Plugin: Loading "cam" tape backend.
18e66 LTFS17085I Plugin: Loading "unified" iosched backend.
18e66 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
18e66 LTFS31223I Opening a device through CAM driver (/dev/sa0)
18e66 LTFS31228I Product ID is 'Ultrium 6-SCSI'
18e66 LTFS31229I Vendor ID is HP
18e66 LTFS31232I Firmware revision is 32BD
18e66 LTFS31233I Drive serial is HU1319VMKC
18e66 LTFS17160I Maximum device block size is 131072.
18e66 LTFS11330I Loading cartridge.
18e66 LTFS11332I Load successful.
18e66 LTFS17157I Changing the drive setting to write-anywhere mode.
18e66 LTFS11005I Mounting the volume from device.
18e66 LTFS31214E Error on locate: msg = NULL (-20802) HU1319VMKC
18e66 LTFS12037E Cannot seek: backend call failed (-20802).
18e66 LTFS11006E Cannot read volume: failed to load the tape.
18e66 LTFS14013E Cannot mount the volume from device.
18e66 LTFS31213I Error on modesense: (pass12:mps0:0:94:0): MODE SENSE(10). CDB: 5a 00 24 00 00 00 00 00 28 00
(pass12:mps0:0:94:0): CAM status: SCSI Status Error
(pass12:mps0:0:94:0): SCSI status: Check Condition
(pass12:mps0:0:94:0): SCSI sense: ILLEGAL REQUEST asc:24,0 (Invalid field in CDB)
(pass12:mps0:0:94:0): Command byte 2 bit 5 is invalid
 (-20501) HU1319VMKC
```

what could be wrong? any suggestions

**Comment by piste-jp-ibm** [comment]
The point is below. The `LOCATE` command failed with `-20802`.

```
18e66 LTFS11005I Mounting the volume from device.
18e66 LTFS31214E Error on locate: msg = NULL (-20802) HU1319VMKC
18e66 LTFS12037E Cannot seek: backend call failed (-20802).
```

It is the `EOD not found` error. Try deep recovery, `ltfsck -z`.

https://github.com/LinearTapeFileSystem/ltfs/blob/f95a9a4463a0e3dbb0b69aa57324a78e4eb80322/src/libltfs/ltfs_error.h#L437

**Comment by ia2115** [comment]
then i get this:

# ltfsck -z
LTFS9015W Setting the locale to 'en_US.UTF-8'. If this is wrong, please set the LANG environment variable before starting ltfsck.
LTFS16000I Starting ltfsck, LTFS version 2.5.0.0 (Prelim), log level 2.
LTFS16088I Launched by "ltfsck -z".
LTFS16089I This binary is built for FreeBSD.
LTFS16090I GCC version is FreeBSD Clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2).
LTFS17087I Kernel version: FreeBSD 12.2-STABLE r369131 GENERIC
.
LTFS16009E Must provide device name.
LTFS16002E Option validation failed.
Usage: ltfsck [options] filesys

filesys                           Device file for the tape drive

Available options are:
  -g, --generation=<generation>   Specify the generation to roll back
  -r, --rollback                  Roll back to the point specified by -g
  -n, --no-rollback               Do not roll back. Verify the point specified by -g (default)
  -f, --full-recovery             Recover extra data blocks into directory _ltfs_lostandfound
  -z, --deep-recovery             Recover EOD missing cartridge.
                                  Some blocks might be erased, but recover to final unmount point
                                  with an index version of at least  2.0.0  or earlier.
                                  (Must be used for a cartridge that cannot be recovered by a normal option.)
  -l, --list-rollback-points      List rollback points
  -m, --full-index-info           Display full index information (Effective only for -l option)
  -v, --traverse=<strategy>       Set traverse mode for listing roll back points. Strategy should be forward or backward. (default: backward)
  -j, --erase-history             Erase history at rollback
  -k, --keep-history              Keep history at rollback (default)
  -q, --quiet                     Suppress informational messages
  -t, --trace                     Enable diagnostic output
      --syslogtrace               Enable diagnostic output to stderr and syslog
  -V, --version                   Version information
  -h, --help                      This help
  -p, --advanced-help             Full help, including advanced options

**Comment by ia2115** [comment]
when i access the tapes i keep getting:
Cannot read volume: block size is 524288, but the device only supports a block size of 131072. is this a value from ltfs or set within the base os? or maybe even a limit on the hba?

**Comment by piste-jp-ibm** [comment]
I think it's depends on HBA or driver.

Please check your HBA supports longer payload transfer (for tape). Or reformat with 131,072 bytes, `mkltfs --blocksize=131072`. 

https://github.com/LinearTapeFileSystem/ltfs/wiki/mkltfs

**Comment by ia2115** [comment]
now tried freebsd 12.2 my old where limit is that 128k and on testing with same hba on 13.2b i get 1mb so seems it os specific. thanks for answers seems like i will resolve this when upgrading my base os next week.. this can be closed thanks a lot.
