### ISSUE TITLE
Creating hard link: OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by simonwaid** [LinearTapeFileSystem/ltfs#397]
**Describe the bug**
Trying to create a hard link on a mounted ltfs system fails with OSError: [Errno 38] Function not implemented

**To Reproduce**
Steps to reproduce the behavior: We first mount the tape, then create a file and try to create a hard link to it.
```
sudo ltfs -o devname=/dev/sg0 /media/tape/
cd /media/tape
touch test
ln test test2
```

**Expected behavior**
I'd expect that a hard link is being created.

**Desktop:**
OS: Ubuntu Linux 22.04, Kernel 6.0.7

**Comment by piste-jp-ibm** [comment]
It is as designed.

**Comment by piste-jp-ibm** [comment]
Close this at this time. Please feel free to reopen if someone have a good idea how to support hard link under LTFS format.
