### ISSUE TITLE
When is unmount completed?

### ISSUE THREAD

**Issue by lostboy7** [LinearTapeFileSystem/ltfs#400]
The readme has the following to say about the 'unmount' functionality: 

"
One thing you need to pay attention to here is, that the unmount command continues to work in the background after it returns. It just initiates a trigger to notify the the ltfs command of the unmount request. Actual unmount is completed when the ltfs command is finished.
"

This raises question -- how does one know when the unmount command, which is continuing to work in the background, actually completes?

I'm using LTFS with an autoloader and scripts, I need to know how to detect the unmount completion so that I may command the robotics to eject and move the tape....

**Comment by piste-jp-ibm** [comment]
You need to detect the completion of the `ltfs` process. I believe you can see the script in the repository.

https://github.com/LinearTapeFileSystem/ltfs/blob/master/init.d/ltfs

**Comment by lostboy7** [comment]
Ah, monitor for exit of the actual process.  Perfect.  Thank you.
