### ISSUE TITLE
Tapes fail to mount after writing

### ISSUE THREAD

**Issue by ggw-** [LinearTapeFileSystem/ltfs#401]
Good day,   

Having a problem with ltfs tapes we are trying to create then mount without luck.  Hoping someone may be able to help out with this.  Thanks in advance! 

Tried on 2 different machines,  2 different tapes with same results.   After formatting the tape with ltfs,  we mount it and write data to it.   Before ejecting we can copy data off the tape.  Once ejected, it won't mount again, complaining about not being able to read label.

-=-=-=-=

Both machines are at LTFS version 2.5.0.0 and Format Spec 2.4.0.

Machine 1 is a VM with PCI passthrough.  We use this daily to read ltfs/tar archive tapes,  this is the first tape we had to write with ltfs.  It is running CentOS 8.7.

```
root@io /usr/local/etc# lsscsi
[2:0:0:0]    disk    VMware   Virtual disk     2.0   /dev/sda 
[3:0:0:0]    cd/dvd  NECVMWar VMware SATA CD00 1.00  /dev/sr0 
[7:0:0:0]    tape    HPE      Ultrium 8-SCSI   M571  /dev/st0 
root@io /usr/local/etc# lspci | grep LSI
13:00.0 Serial Attached SCSI controller: Broadcom / LSI SAS2008 PCI-Express Fusion-MPT SAS-2 [Falcon] (rev 03)
```

Machine two is a Dell physical server with 2 drives connected via FC.  With CentOS 7.9.

```
[root@backup01 ~]# lsscsi
[0:3:111:0]  disk    DELL     PERC H755 Front  5.21  /dev/sda 
[9:0:0:0]    tape    IBM      ULT3580-HH8      P381  /dev/st0 
[11:0:0:0]   tape    IBM      ULT3580-HH8      P381  /dev/st1 
[11:0:0:1]   mediumx IBM      3573-TL          1502  /dev/sch0
[root@backup01 ~]# lspci | grep Fibre
25:00.0 Fibre Channel: QLogic Corp. ISP2722-based 16/32Gb Fibre Channel to PCIe Adapter (rev 01)
25:00.1 Fibre Channel: QLogic Corp. ISP2722-based 16/32Gb Fibre Channel to PCIe Adapter (rev 01)
```

=-=-=-=

Built and installed from source,  first trying without passing arguments to configure,  then with the "--enable-buggy-ifs".  No difference in behaviour observed.  

1. mkltfs -d /dev/st0 -s REPO01
2. ltfs -o devname=/dev/st0 /mnt/tape
3. copy data to /mnt/tape
4. after done,  copy data from tape to local filesystem - works.
5. rewind tape (mt -f /dev/st0 rewind)
6. eject tape (mt -f /dev/st0 eject)
7. attempt to mount tape:  ltfs -o devname=/dev/st0 /mnt/tape
It produces the below output:

```
[root@backup01 ltfs]# ltfs -o devname=/dev/st0 /mnt/tape
9bba LTFS14000I LTFS starting, LTFS version 2.5.0.0 (Prelim), log level 2.
9bba LTFS14058I LTFS Format Specification version 2.4.0.
9bba LTFS14104I Launched by "ltfs -o devname=/dev/st0 /mnt/tape".
9bba LTFS14105I This binary is built for Linux (x86_64).
9bba LTFS14106I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-44).
9bba LTFS17087I Kernel version: Linux version 3.10.0-1160.71.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 28 15:37:28 UTC 2022 i386.
9bba LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
9bba LTFS17089I Distribution: NAME="CentOS Linux".
9bba LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
9bba LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
9bba LTFS14063I Sync type is "time", Sync time is 300 sec.
9bba LTFS17085I Plugin: Loading "sg" tape backend.
9bba LTFS17085I Plugin: Loading "unified" iosched backend.
9bba LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
9bba LTFS30209I Opening a device through sg-ibmtape driver (/dev/st0).
9bba LTFS30250I Opened the SCSI tape device 0.0.0.-1 (/dev/st0).
9bba LTFS30207I Vendor ID is IBM     .
9bba LTFS30208I Product ID is ULT3580-HH8     .
9bba LTFS30214I Firmware revision is P381.
9bba LTFS30215I Drive serial is 118460D065.
9bba LTFS30285I The reserved buffer size of /dev/st0 is 524288.
9bba LTFS30294I Setting up timeout values from RSOC.
9bba LTFS17160I Maximum device block size is 1048576.
9bba LTFS11330I Loading cartridge.
9bba LTFS30252I Logical block protection is disabled.
9bba LTFS11332I Load successful.
9bba LTFS17157I Changing the drive setting to write-anywhere mode.
9bba LTFS11005I Mounting the volume from device.
9bba LTFS30252I Logical block protection is disabled.
9bba LTFS30820I (no message found).
9bba LTFS30263I READ returns No Additional Sense Information (-20002) /dev/st0.
9bba LTFS12049E Cannot read: backend call failed (-20002).
9bba LTFS11174E Cannot read ANSI label: read failed (-20002).
9bba LTFS11170E Failed to read label (-20002) from partition 0.
9bba LTFS11009E Cannot read volume: failed to read partition labels.
9bba LTFS14013E Cannot mount the volume from device.
9bba LTFS30252I Logical block protection is disabled.
```

-=-=-=-=-=
```
  125 mkltfs -d /dev/st0 -s REPO01
  127  ltfs -o devname=/dev/st0 /mnt/tape/
  128  cd /mnt/systems/pictures/
  129  ls
  130  screen
  131  cp *.jpg /mnt/tape
  132 pwd
  133 cp /mnt/tape/* ~greg/
  132  ls -ltr /home/greg
```

Pictures copied over to my home dir.   This is before un-mounting tape.

```
[root@backup01 tape]# df -h
__SNIP__
fs03:/systems         941T  836T  106T  89% /mnt/systems
ltfs:/dev/st0             11T   18M   11T   1% /mnt/tape
```

**Comment by ggw-** [comment]
Thought this might help.  this is the output during the formatting of tape,  then initial mounting.  

Its odd that we can mount the tape after formating it but can't after writing data to it.  Does that make sense or point to anything?


[root@backup01 ltfs]# mkltfs -d /dev/st0 -n DW0025 -f -t 
LTFS15000I Starting mkltfs, LTFS version 2.5.0.0 (Prelim), log level 3.
LTFS15041I Launched by "mkltfs -d /dev/st0 -n DW0025 -f -t".
LTFS15042I This binary is built for Linux (x86_64).
LTFS15043I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-44).
LTFS17087I Kernel version: Linux version 3.10.0-1160.71.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 28 15:37:28 UTC 2022 i386.
LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
LTFS17089I Distribution: NAME="CentOS Linux".
LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
LTFS15025D Validating command line options.
LTFS15037D Command line options are valid.
LTFS15003I Formatting device '/dev/st0'.
LTFS15004I LTFS volume blocksize: 524288.
LTFS15005I Index partition placement policy: None.

LTFS11337I Update index-dirty flag (1) - NO_BARCODE (0x0xa7ef30).
LTFS15006D Opening the device.
LTFS17085I Plugin: Loading "sg" tape backend.
LTFS30209I Opening a device through sg-ibmtape driver (/dev/st0).
LTFS30250I Opened the SCSI tape device 0.0.0.-1 (/dev/st0).
LTFS30207I Vendor ID is IBM     .
LTFS30208I Product ID is ULT3580-HH8     .
LTFS30214I Firmware revision is P381.
LTFS30215I Drive serial is 118460D065.
LTFS30285I The reserved buffer size of /dev/st0 is 524288.
LTFS30294I Setting up timeout values from RSOC.
LTFS12023D Reserving device.
LTFS30392D Backend reserve (PRO) 118460D065.
LTFS12028D Unlocking medium.
LTFS30392D Backend allow medium removal 118460D065.
LTFS30392D Backend read block limits 118460D065.
LTFS17160I Maximum device block size is 1048576.
LTFS11330I Loading cartridge.
LTFS30392D Backend load 118460D065.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D065.
LTFS12026D Locking medium in the drive.
LTFS30392D Backend prevent medium removal 118460D065.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D065.
LTFS30392D Backend sg_set_default Resetting LBP.
LTFS30393D Backend LBP Enable: 0 .
LTFS30393D Backend LBP Method: 2 .
LTFS30252I Logical block protection is disabled.
LTFS30392D Backend read block limits 118460D065.
LTFS11332I Load successful.
LTFS17157I Changing the drive setting to write-anywhere mode.
LTFS15007D Device opened.
LTFS15049I Checking the medium (load).
LTFS30392D Backend load 118460D065.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D065.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D065.
LTFS30392D Backend sg_set_default Resetting LBP.
LTFS30393D Backend LBP Enable: 0 .
LTFS30393D Backend LBP Method: 2 .
LTFS30252I Logical block protection is disabled.
LTFS30392D Backend read block limits 118460D065.
LTFS15010I Creating data partition b on SCSI partition 1.
LTFS15011I Creating index partition a on SCSI partition 0.
LTFS11095E Cannot format: the medium is write protected.
LTFS15012E Failed to format the medium.
LTFS12028D Unlocking medium.
LTFS30392D Backend allow medium removal 118460D065.
LTFS12025D Releasing device.
LTFS30392D Backend release (PRO) 118460D065.
LTFS30393D Backend LBP Enable: 0 .
LTFS30393D Backend LBP Method: 2 .
LTFS30252I Logical block protection is disabled.
LTFS15023I Formatting failed.
[root@backup01 ltfs]# mkltfs -d /dev/st1 -n DW0025 -f -t 
LTFS15000I Starting mkltfs, LTFS version 2.5.0.0 (Prelim), log level 3.
LTFS15041I Launched by "mkltfs -d /dev/st1 -n DW0025 -f -t".
LTFS15042I This binary is built for Linux (x86_64).
LTFS15043I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-44).
LTFS17087I Kernel version: Linux version 3.10.0-1160.71.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 28 15:37:28 UTC 2022 i386.
LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
LTFS17089I Distribution: NAME="CentOS Linux".
LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
LTFS15025D Validating command line options.
LTFS15037D Command line options are valid.
LTFS15003I Formatting device '/dev/st1'.
LTFS15004I LTFS volume blocksize: 524288.
LTFS15005I Index partition placement policy: None.

LTFS11337I Update index-dirty flag (1) - NO_BARCODE (0x0x1532f30).
LTFS15006D Opening the device.
LTFS17085I Plugin: Loading "sg" tape backend.
LTFS30209I Opening a device through sg-ibmtape driver (/dev/st1).
LTFS30250I Opened the SCSI tape device 0.0.0.-1 (/dev/st1).
LTFS30207I Vendor ID is IBM     .
LTFS30208I Product ID is ULT3580-HH8     .
LTFS30214I Firmware revision is P381.
LTFS30215I Drive serial is 118460D05B.
LTFS30285I The reserved buffer size of /dev/st1 is 524288.
LTFS30294I Setting up timeout values from RSOC.
LTFS12023D Reserving device.
LTFS30392D Backend reserve (PRO) 118460D05B.
LTFS12028D Unlocking medium.
LTFS30392D Backend allow medium removal 118460D05B.
LTFS30392D Backend read block limits 118460D05B.
LTFS17160I Maximum device block size is 1048576.
LTFS11330I Loading cartridge.
LTFS30392D Backend load 118460D05B.

LTFS30398D Backend readpos: (0, 0) FM = 0 118460D05B.
LTFS12026D Locking medium in the drive.
LTFS30392D Backend prevent medium removal 118460D05B.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D05B.
LTFS30392D Backend sg_set_default Resetting LBP.
LTFS30393D Backend LBP Enable: 0 .
LTFS30393D Backend LBP Method: 2 .
LTFS30252I Logical block protection is disabled.
LTFS30392D Backend read block limits 118460D05B.
LTFS11332I Load successful.
LTFS17157I Changing the drive setting to write-anywhere mode.
LTFS15007D Device opened.
LTFS15049I Checking the medium (load).
LTFS30392D Backend load 118460D05B.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D05B.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D05B.
LTFS30392D Backend sg_set_default Resetting LBP.
LTFS30393D Backend LBP Enable: 0 .
LTFS30393D Backend LBP Method: 2 .
LTFS30252I Logical block protection is disabled.
LTFS30392D Backend read block limits 118460D05B.
LTFS15010I Creating data partition b on SCSI partition 1.
LTFS15011I Creating index partition a on SCSI partition 0.
LTFS30392D Backend read block limits 118460D05B.
LTFS17165I Resetting the medium's capacity proportion.
LTFS30392D Backend load 118460D05B.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D05B.
LTFS30393D Backend setcap: 65535 118460D05B.
LTFS30201D CDB check condition: sense = 062a01, Mode Parameters Changed.
LTFS30204D TEST_UNIT_READY (0x00) expected error -20604.
LTFS11097I Partitioning the medium.
LTFS30392D Backend load 118460D05B.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D05B.
LTFS30201D CDB check condition: sense = 013700, Mode Parameters Rounded.
LTFS30204D MODESELECT (0x55) expected error -20101.
LTFS30263I MODESELECT returns Mode Parameters Rounded (-20101) /dev/st1.
LTFS30392D Backend format 118460D05B.
LTFS11100I Writing label to partition b.
LTFS30397D Backend locate: (1, 0) 118460D05B.
LTFS30398D Backend readpos: (1, 0) FM = 0 118460D05B.
LTFS30394D Backend write file marks: 1 118460D05B.
LTFS30398D Backend readpos: (1, 2) FM = 1 118460D05B.
LTFS30394D Backend write file marks: 1 118460D05B.
LTFS30398D Backend readpos: (1, 4) FM = 2 118460D05B.
LTFS11278I Writing index to partition b.
LTFS30201D CDB check condition: sense = 052400, Invalid Field in CDB.
LTFS30205I READ_ATTR (0x8c) returns -20501.
LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/st1.
LTFS30233I Cannot read attribute (-20501).
LTFS11336I The attribute does not exist. Ignore the expected error.
LTFS17235I Writing index of NO_BARCODE to b (Reason: Format, 0 files) 118460D05B.
LTFS30394D Backend write file marks: 1 118460D05B.
LTFS30398D Backend readpos: (1, 5) FM = 3 118460D05B.
LTFS30394D Backend write file marks: 1 118460D05B.
LTFS30398D Backend readpos: (1, 7) FM = 4 118460D05B.
LTFS17236I Wrote index of NO_BARCODE (Gen = 1, Part = b, Pos = 5, 118460D05B).
LTFS11337I Update index-dirty flag (0) - NO_BARCODE (0x0x1532f30).
LTFS11100I Writing label to partition a.
LTFS30397D Backend locate: (0, 0) 118460D05B.
LTFS30398D Backend readpos: (0, 0) FM = 0 118460D05B.
LTFS30394D Backend write file marks: 1 118460D05B.
LTFS30398D Backend readpos: (0, 2) FM = 1 118460D05B.
LTFS30394D Backend write file marks: 1 118460D05B.
LTFS30398D Backend readpos: (0, 4) FM = 2 118460D05B.
LTFS11278I Writing index to partition a.
LTFS30201D CDB check condition: sense = 052400, Invalid Field in CDB.
LTFS30205I READ_ATTR (0x8c) returns -20501.
LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/st1.
LTFS30233I Cannot read attribute (-20501).
LTFS11336I The attribute does not exist. Ignore the expected error.
LTFS30394D Backend write file marks: 0 118460D05B.
LTFS30398D Backend readpos: (0, 4) FM = 2 118460D05B.
LTFS17235I Writing index of NO_BARCODE to a (Reason: Format, 0 files) 118460D05B.
LTFS30394D Backend write file marks: 1 118460D05B.
LTFS30398D Backend readpos: (0, 5) FM = 3 118460D05B.
LTFS30394D Backend write file marks: 1 118460D05B.
LTFS30398D Backend readpos: (0, 7) FM = 4 118460D05B.
LTFS17236I Wrote index of NO_BARCODE (Gen = 1, Part = a, Pos = 5, 118460D05B).
LTFS15013I Volume UUID is: d2cf9bf9-d020-46d1-bbcb-589e0401588a.

LTFS15019I Volume capacity is 11712 GB.
LTFS15020D Closing the device.
LTFS12028D Unlocking medium.
LTFS30392D Backend allow medium removal 118460D05B.
LTFS12025D Releasing device.
LTFS30392D Backend release (PRO) 118460D05B.
LTFS30393D Backend LBP Enable: 0 .
LTFS30393D Backend LBP Method: 2 .
LTFS30252I Logical block protection is disabled.
LTFS15022D Device closed.
LTFS15024I Medium formatted successfully.
[root@backup01 ltfs]#


[root@backup01 ltfs]# ltfs -o devname=/dev/st1 /mnt/tape
9e8b LTFS14000I LTFS starting, LTFS version 2.5.0.0 (Prelim), log level 2.
9e8b LTFS14058I LTFS Format Specification version 2.4.0.
9e8b LTFS14104I Launched by "ltfs -o devname=/dev/st1 /mnt/tape".
9e8b LTFS14105I This binary is built for Linux (x86_64).
9e8b LTFS14106I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-44).
9e8b LTFS17087I Kernel version: Linux version 3.10.0-1160.71.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 28 15:37:28 UTC 2022 i386.
9e8b LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
9e8b LTFS17089I Distribution: NAME="CentOS Linux".
9e8b LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
9e8b LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
9e8b LTFS14063I Sync type is "time", Sync time is 300 sec.
9e8b LTFS17085I Plugin: Loading "sg" tape backend.
9e8b LTFS17085I Plugin: Loading "unified" iosched backend.
9e8b LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
9e8b LTFS30209I Opening a device through sg-ibmtape driver (/dev/st1).
9e8b LTFS30250I Opened the SCSI tape device 0.0.0.-1 (/dev/st1).
9e8b LTFS30207I Vendor ID is IBM     .
9e8b LTFS30208I Product ID is ULT3580-HH8     .
9e8b LTFS30214I Firmware revision is P381.
9e8b LTFS30215I Drive serial is 118460D05B.
9e8b LTFS30285I The reserved buffer size of /dev/st1 is 524288.
9e8b LTFS30294I Setting up timeout values from RSOC.
9e8b LTFS17160I Maximum device block size is 1048576.
9e8b LTFS11330I Loading cartridge.
9e8b LTFS30252I Logical block protection is disabled.
9e8b LTFS11332I Load successful.
9e8b LTFS17157I Changing the drive setting to write-anywhere mode.
9e8b LTFS11005I Mounting the volume from device.
9e8b LTFS30252I Logical block protection is disabled.
9e8b LTFS17227I Tape attribute: Vendor = IBM     .
9e8b LTFS17227I Tape attribute: Application Name = LTFS                            .
9e8b LTFS17227I Tape attribute: Application Version = 2.5.0.0 .
9e8b LTFS17227I Tape attribute: Medium Label = DW0025.
9e8b LTFS17228I Tape attribute: Text Localization ID = 0x81.
9e8b LTFS17227I Tape attribute: Barcode =                                 .
9e8b LTFS17227I Tape attribute: Application Format Version = 2.4.0           .
9e8b LTFS17228I Tape attribute: Volume Lock Status = 0x00.
9e8b LTFS17227I Tape attribute: Media Pool name = .
9e8b LTFS11031I Volume mounted successfully. NO_BARCODE : Gen = 1 / (a, 5) -> (b, 5) / 118460D05B.
9e8b LTFS14122I Index will not be captured.
9e8b LTFS14111I Initial setup completed successfully.
9e8b LTFS14112I Invoke 'mount' command to check the result of final setup.
9e8b LTFS14113I Specified mount point is listed if succeeded.
[root@backup01 ltfs]# 
[root@backup01 ltfs]# df -h | grep tape
ltfs:/dev/st1             11T   18M   11T   1% /mnt/tape
[root@backup01 ltfs]# 


[root@backup01 ~]# cd ~greg
[root@backup01 greg]# ls
47BY-3a_1.3.1.jpg     47CC-1a_1.17.1.jpg  47CE-1c_1.28.1.jpg  48B-4c_1.50.1.jpg  B47-1h_1.62.1.jpg
__SNIP__
[root@backup01 greg]# mkdir /mnt/tape/foobar
[root@backup01 greg]# cp *.jpg !$
cp *.jpg /mnt/tape/foobar
[root@backup01 greg]# sync
[root@backup01 greg]# ls /mnt/tape/foobar/
47BY-3a_1.3.1.jpg     47CC-1a_1.17.1.jpg  47CE-1c_1.28.1.jpg  48B-4c_1.50.1.jpg  B47-1h_1.62.1.jpg
__SNIP__
[root@backup01 greg]# du -sh !$
du -sh /mnt/tape/foobar/
43M	/mnt/tape/foobar/
[root@backup01 greg]# du -sh .
44M	.
[root@backup01 greg]# mkdir /tmp/foobar
[root@backup01 greg]# cp /mnt/tape/foobar/*.jpg !$/
cp /mnt/tape/foobar/*.jpg /tmp/foobar/
[root@backup01 greg]# du -sh /tmp/foobar/
44M	/tmp/foobar/

**Comment by piste-jp-ibm** [comment]
I cannot understand why you want to try with LTFS with the device `/dev/st0`.

Please refer the quick start section in the [README.md](https://github.com/LinearTapeFileSystem/ltfs#how-to-use-the-ltfs-quick-start) and follow teh instructions.

**Comment by ggw-** [comment]
Thanks,  if you need to understand it is because that is what I understood to use after reading an HP document.

 ( https://ftp1.overlandtandberg.com/neo/LTFS/LTO-5,6/LTFS%20User%20Guide%20-%20Mac%20&%20Linux.pdf )

Thanks for pointing that out and have a good weekend.

**Comment by piste-jp-ibm** [comment]
> Thanks, if you need to understand it is because that is what I understood to use after reading an HP document.

I got. The doc you mentioned is the instruction for using their (HP's) implementation.

The LTFS in this repository is supporting some HP drives but it is not same as HP's implementation. (I believe they are providing their code based on this project, but they shall change something from this repository. So it is not a quite same.)

You need to understand to follow the instruction in the repository if you want to use the code here.
