### ISSUE TITLE
Support HPE/LTO9

### ISSUE THREAD

**Issue by proceau** [LinearTapeFileSystem/ltfs#402]
** Support HPE/LTO9 **

1. compile last master branch
2. add hp_tape.c the support of LTO9
3. mkltfs of lecteur ( after calibration of tape ) ( see annexe A )
4. ltfs of tape for mount  ( see annexe B )

** annexe A **
mkltfs --device=/dev/tape3n
LTFS15000I Starting mkltfs, LTFS version 2.5.0.0 (Prelim), log level 2.
LTFS15041I Launched by "mkltfs --device=/dev/tape3n".
LTFS15042I This binary is built for Linux (x86_64).
LTFS15043I GCC version is 8.3.0.
LTFS17087I Kernel version: Linux version 4.19.269-amd64 (root@sqk-msl) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Wed Dec 14 17:27:13 CET 2022 i386.
LTFS17089I Distribution: PRETTY_NAME="Debian GNU/Linux 10 (buster)".
LTFS15003I Formatting device '/dev/tape3n'.
LTFS15004I LTFS volume blocksize: 524288.
LTFS15005I Index partition placement policy: None.

LTFS11337I Update index-dirty flag (1) - NO_BARCODE (0x0x559a420072a0).
LTFS17085I Plugin: Loading "sg" tape backend.
LTFS30209I Opening a device through sg-ibmtape driver (/dev/tape3n).
LTFS30250I Opened the SCSI tape device 0.0.0.-1 (/dev/tape3n).
LTFS30207I Vendor ID is HPE     .
LTFS30208I Product ID is Ultrium 9-SCSI  .
LTFS30214I Firmware revision is PA61.
LTFS30215I Drive serial is XXXXXX.
LTFS30285I The reserved buffer size of /dev/tape3n is 1048576.
LTFS30294I Setting up timeout values from RSOC.
LTFS17160I Maximum device block size is 1048576.
LTFS11330I Loading cartridge.
LTFS11332I Load successful.
LTFS17157I Changing the drive setting to write-anywhere mode.
LTFS15049I Checking the medium (mount).
LTFS15047E Medium is already formatted (0).
LTFS15048I Need to specify -f or --force option to format this medium.
LTFS30252I Logical block protection is disabled.
LTFS15023I Formatting failed.
root@sqk-msl:/home/src/ltfs# /home/bin/ltfs25/bin/mkltfs --device=/dev/tape3n   -f
LTFS15000I Starting mkltfs, LTFS version 2.5.0.0 (Prelim), log level 2.
LTFS15041I Launched by "/home/bin/ltfs25/bin/mkltfs --device=/dev/tape3n -f".
LTFS15042I This binary is built for Linux (x86_64).
LTFS15043I GCC version is 8.3.0.
LTFS17087I Kernel version: Linux version 4.19.269-amd64 (root@sqk-msl) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Wed Dec 14 17:27:13 CET 2022 i386.
LTFS17089I Distribution: PRETTY_NAME="Debian GNU/Linux 10 (buster)".
LTFS15003I Formatting device '/dev/tape3n'.
LTFS15004I LTFS volume blocksize: 524288.
LTFS15005I Index partition placement policy: None.

LTFS11337I Update index-dirty flag (1) - NO_BARCODE (0x0x56316f4ed2a0).
LTFS17085I Plugin: Loading "sg" tape backend.
LTFS30209I Opening a device through sg-ibmtape driver (/dev/tape3n).
LTFS30250I Opened the SCSI tape device 0.0.0.-1 (/dev/tape3n).
LTFS30207I Vendor ID is HPE     .
LTFS30208I Product ID is Ultrium 9-SCSI  .
LTFS30214I Firmware revision is PA61.
LTFS30215I Drive serial is XXXXXXX.
LTFS30285I The reserved buffer size of /dev/tape3n is 1048576.
LTFS30294I Setting up timeout values from RSOC.
LTFS17160I Maximum device block size is 1048576.
LTFS11330I Loading cartridge.
LTFS11332I Load successful.
LTFS17157I Changing the drive setting to write-anywhere mode.
LTFS15049I Checking the medium (load).
LTFS15010I Creating data partition b on SCSI partition 1.
LTFS15011I Creating index partition a on SCSI partition 0.
LTFS17165I Resetting the medium's capacity proportion.
LTFS11097I Partitioning the medium.
LTFS30263I MODESELECT returns Mode Parameters Rounded (-20101) /dev/tape3n.
LTFS11100I Writing label to partition b.
LTFS11278I Writing index to partition b.
LTFS30205I READ_ATTR (0x8c) returns -20501.
LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/tape3n.
LTFS30233I Cannot read attribute (-20501).
LTFS11336I The attribute does not exist. Ignore the expected error.
LTFS17235I Writing index of NO_BARCODE to b (Reason: Format, 0 files) 8036B562D7.
LTFS17236I Wrote index of NO_BARCODE (Gen = 1, Part = b, Pos = 5, 8036B562D7).
LTFS11337I Update index-dirty flag (0) - NO_BARCODE (0x0x56316f4ed2a0).
LTFS11100I Writing label to partition a.
LTFS11278I Writing index to partition a.
LTFS30205I READ_ATTR (0x8c) returns -20501.
LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/tape3n.
LTFS30233I Cannot read attribute (-20501).
LTFS11336I The attribute does not exist. Ignore the expected error.
LTFS17235I Writing index of NO_BARCODE to a (Reason: Format, 0 files) 8036B562D7.
LTFS17236I Wrote index of NO_BARCODE (Gen = 1, Part = a, Pos = 5, 8036B562D7).
LTFS15013I Volume UUID is: 6398e060-1d81-4263-8573-ce4eefdd44b5.

LTFS15019I Volume capacity is 17550 GB.
LTFS30252I Logical block protection is disabled.
LTFS15024I Medium formatted successfully.

** Annexe B **
ltfs  -o devname=/dev/tape3n /home/drive3 -o sync_type=time@180
5075 LTFS14000I LTFS starting, LTFS version 2.5.0.0 (Prelim), log level 2.
5075 LTFS14058I LTFS Format Specification version 2.4.0.
5075 LTFS14104I Launched by "bin/ltfs -o devname=/dev/tape3n /home/drive3 -o sync_type=time@180".
5075 LTFS14105I This binary is built for Linux (x86_64).
5075 LTFS14106I GCC version is 8.3.0.
5075 LTFS17087I Kernel version: Linux version 4.19.269-amd64 (root@sqk-msl) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Wed Dec 14 17:27:13 CET 2022 i386.
5075 LTFS17089I Distribution: PRETTY_NAME="Debian GNU/Linux 10 (buster)".
5075 LTFS14063I Sync type is "time", Sync time is 10800 sec.
5075 LTFS17085I Plugin: Loading "sg" tape backend.
5075 LTFS17085I Plugin: Loading "unified" iosched backend.
5075 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
5075 LTFS30209I Opening a device through sg-ibmtape driver (/dev/tape3n).
5075 LTFS30250I Opened the SCSI tape device 0.0.0.-1 (/dev/tape3n).
5075 LTFS30207I Vendor ID is HPE     .
5075 LTFS30208I Product ID is Ultrium 9-SCSI  .
5075 LTFS30214I Firmware revision is PA61.
5075 LTFS30215I Drive serial is XXXXXX.
5075 LTFS30285I The reserved buffer size of /dev/tape3n is 1048576.
5075 LTFS30294I Setting up timeout values from RSOC.
5075 LTFS17160I Maximum device block size is 1048576.
5075 LTFS11330I Loading cartridge.
5075 LTFS11332I Load successful.
5075 LTFS17157I Changing the drive setting to write-anywhere mode.
5075 LTFS11005I Mounting the volume from device.
5075 LTFS30216W Length mismatch is detected. (Act = 524288, resid = 0, resid_sense = 523294).
5075 LTFS30216W Length mismatch is detected. (Act = 524288, resid = 0, resid_sense = 523294).
5075 LTFS12049E Cannot read: backend call failed (-21716).
5075 LTFS17039E XML parser: failed to read a block from the medium (-21716).
5075 LTFS17037E XML parser: failed to read from XML stream.
5075 LTFS17273E XML parser: Detected an I/O error on reading an index from the tape (-21716).
5075 LTFS17016E Cannot parse index direct from medium (-21716).
5075 LTFS11194W Cannot read index: failed to read and parse XML data (-21716).
5075 LTFS11024E Cannot mount volume: read index failed on the index partition.
5075 LTFS14013E Cannot mount the volume from device.
5075 LTFS30252I Logical block protection is disabled.

**Comment by piste-jp-ibm** [comment]
It looks this is a dup of #383. 

Please search issues by `LTFS30216W`. I think you can see multiple similar problems.

**Comment by proceau** [comment]
with my patch + the parameter it's works \o/

**Comment by piste-jp-ibm** [comment]
Closing this because it looks it is working fine now.
