### ISSUE TITLE
Show fuse_main() error codes on logs

### ISSUE THREAD

**Issue by amissael95** [LinearTapeFileSystem/ltfs#403]
**Is your feature request related to a problem? Please describe.**
According to following documentation https://libfuse.github.io/doxygen/fuse_8h.html#ac99b844cee7aaa8fb4e35df5b5488d82.
The following error codes may be returned from **fuse_main()
1: Invalid option arguments 
2: No mount point specified 
3: FUSE setup failed
4: Mounting failed 
5: Failed to daemonize (detach from session) 
6: Failed to set up signal handlers 
7: An error occurred during the life of the file system

but when fuse_main() is used on **single_drive_main** function, the return code is not logged in case of a fuse_main failure. 

**Describe the solution you'd like**
In case of an error, it would be very useful to know if fuse_main() was the reason of the failure so the solution is to add a new log code to show the return code of fuse_main in case it is different from 0.

**Describe alternatives you've considered**
Use one of the existing log codes, but none is really related to fuse_main() errors. 

**Additional context**
This will help to troubleshoot an issue related with fuse library.

**Comment by piste-jp-ibm** [comment]
@amissael95 

Please assign an issue to yourself, if you have an plan to work on it before opening an PR.
