### ISSUE TITLE
sg take backend - why

### ISSUE THREAD

**Issue by RlckAstley** [LinearTapeFileSystem/ltfs#420]
I use st, not sg. Not sure what's going on and can't find documentation

**Comment by piste-jp-ibm** [comment]
Basically, the `st` driver is an adapter that user can access to tape device with the POSIX file system call, like `open(), close(), write(), read() ...`.

On the other hand, LTFS has really fine grained error handling against tape device, the basic command set of `st` is not goos for this fine grained error handling and `sg` device and low level SCSI command is much nicer than `st` command set.

**Comment by piste-jp-ibm** [comment]
Close because no activities from 8/14.
