### ISSUE TITLE
"Unsupported drive" with HPE HH LTO-9 on 2.4-stable on CentOS 7.9

### ISSUE THREAD

**Issue by JoakimZiegler** [LinearTapeFileSystem/ltfs#427]
**Describe the bug**
I'm trying to mount a tape (previously formatted) on an HPE LTO-9 drive, but I'm getting "Unsupported drive". I've just built LTFS from source from 2.4-stable.

I have a CentOS system with two LTO drives on it, a Quantum LTO-7 and a new HPE LTO-9. Since the manufacturer-provided RPM packages of LTFS only support their respective hardware, I decided to install 2.4-stable from source. This works fine with the Quantum LTO-7 drive, but when I try to mount a tape from the HPE LTO-9 drive, it tells me the device is unspported. The drive also does not show up when doing ltfs -o device_list

**Screenshots**
[code]
[root@shinjuku test]# /usr/local/bin/ltfs /mnt/ltfs2 -o devname=/dev/sg74,sync_type=time@20
b3a LTFS14000I LTFS starting, LTFS version 2.4.5.1 (Prelim), log level 2.
b3a LTFS14058I LTFS Format Specification version 2.4.0.
b3a LTFS14104I Launched by "/usr/local/bin/ltfs /mnt/ltfs2 -o devname=/dev/sg74,sync_type=time@20".
b3a LTFS14105I This binary is built for Linux (x86_64).
b3a LTFS14106I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-44).
b3a LTFS17087I Kernel version: Linux version 3.10.0-1160.92.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 20 11:48:01 UTC 2023 i386.
b3a LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
b3a LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
b3a LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
b3a LTFS17089I Distribution: NAME="CentOS Linux".
b3a LTFS14063I Sync type is "time", Sync time is 1200 sec.
b3a LTFS17085I Plugin: Loading "sg" tape backend.
b3a LTFS17085I Plugin: Loading "unified" iosched backend.
b3a LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
b3a LTFS30209I Opening a device through sg-ibmtape driver (/dev/sg74).
b3a LTFS30213I Unsupported Drive 'HPE     ' / 'Ultrium 9-SCSI  '.
b3a LTFS12012E Cannot open device: failed backend open call.
b3a LTFS10004E Cannot open device '/dev/sg74'
[/code]

**Desktop (please complete the following information):**
 - OS: CentOS 7.9
 - Kernel: 3.10.0-1160.92.1.el7.x86_64

**Comment by JoakimZiegler** [comment]
Investigating a bit further, it seems that although README.md for 2.4-stable lists HP LTO-9 drives as supported, the actual hp_supported_drives list in ltfs/src/tape_drivers/hp_tape.c only lists up to LTO-8 as supported. Now the question becomes, is the README file wrong, or is the source code wrong? Is it safe to add LTO-9 to the list and recompile?

**Comment by piste-jp-ibm** [comment]
Hi, Sorry for our confusable description.

README.md is wrong. Please add the line into `hp_tape.c` and try. It might work correctly.

```C
TAPEDRIVE( HPE_VENDOR_ID, "Ultrium 9-SCSI",  VENDOR_HP, DRIVE_LTO9,    "[Ultrium 9-SCSI]" ),  /* HPE Ultrium Gen 9 */
```

**Comment by JoakimZiegler** [comment]
@piste-jp-ibm Thank you, but should that VENDOR_HP field be there? The entry for LTO-8 in that list look like this, and all the entries have 4 fields:

`TAPEDRIVE( HPE_VENDOR_ID, "Ultrium 8-SCSI",  DRIVE_LTO8,    "[Ultrium 8-SCSI]" ),  /* HPE Ultrium Gen 8 */`

**Comment by piste-jp-ibm** [comment]
Oops, it's for the `master` branch.

You are right, the line below is good for the `v2.4-stable` branch.

```C
TAPEDRIVE( HPE_VENDOR_ID, "Ultrium 9-SCSI",  DRIVE_LTO9,    "[Ultrium 9-SCSI]" ),  /* HPE Ultrium Gen 9 */
```

**Comment by JoakimZiegler** [comment]
Thank you, that seems to work, the drive shows up in the list of valid devices, and I can mount the tape. However, when mounting, I do get a couple of messages I haven't seen before, here's the output:

`[root@shinjuku ~]# /usr/local/bin/ltfs /mnt/ltfs2 -o devname=/dev/sg74,sync_type=time@20
f7b LTFS14000I LTFS starting, LTFS version 2.4.5.1 (Prelim), log level 2.
f7b LTFS14058I LTFS Format Specification version 2.4.0.
f7b LTFS14104I Launched by "/usr/local/bin/ltfs /mnt/ltfs2 -o devname=/dev/sg74,sync_type=time@20".
f7b LTFS14105I This binary is built for Linux (x86_64).
f7b LTFS14106I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-44).
f7b LTFS17087I Kernel version: Linux version 3.10.0-1160.92.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 20 11:48:01 UTC 2023 i386.
f7b LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
f7b LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
f7b LTFS17089I Distribution: CentOS Linux release 7.9.2009 (Core).
f7b LTFS17089I Distribution: NAME="CentOS Linux".
f7b LTFS14063I Sync type is "time", Sync time is 1200 sec.
f7b LTFS17085I Plugin: Loading "sg" tape backend.
f7b LTFS17085I Plugin: Loading "unified" iosched backend.
f7b LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
f7b LTFS30209I Opening a device through sg-ibmtape driver (/dev/sg74).
f7b LTFS30250I Opened the SCSI tape device 1.0.71.0 (/dev/sg74).
f7b LTFS30207I Vendor ID is HPE     .
f7b LTFS30208I Product ID is Ultrium 9-SCSI  .
f7b LTFS30214I Firmware revision is Q3F9.
f7b LTFS30215I Drive serial is HUJ312FK2J.
f7b LTFS30285I The reserved buffer size of /dev/sg74 is 524288.
f7b LTFS30205I RSOC (0xa3) returns -20601.
f7b LTFS30263I RSOC returns Not Ready to Ready Transition, Medium May Have Changed (-20601) /dev/sg74.
f7b LTFS30294I Setting up timeout values from vendor and device.
f7b LTFS17160I Maximum device block size is 1048576.
f7b LTFS11330I Loading cartridge.
f7b LTFS11332I Load successful.
f7b LTFS17157I Changing the drive setting to write-anywhere mode.
f7b LTFS11005I Mounting the volume.
f7b LTFS30205I READ_ATTR (0x8c) returns -20501.
f7b LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/sg74.
f7b LTFS30205I READ_ATTR (0x8c) returns -20501.
f7b LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/sg74.
f7b LTFS30205I READ_ATTR (0x8c) returns -20501.
f7b LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/sg74.
f7b LTFS30233I Cannot read attribute (-20501).
f7b LTFS17227I Tape attribute: Vendor = HPE     .
f7b LTFS17227I Tape attribute: Application Name = LTFS                            .
f7b LTFS17227I Tape attribute: Application Version = 3.5.0   .
f7b LTFS17227I Tape attribute: Medium Label = veranda_004.
f7b LTFS17228I Tape attribute: Text Localization ID = 0x00.
f7b LTFS17227I Tape attribute: Barcode = .
f7b LTFS17227I Tape attribute: Application Format Version = 2.4.0           .
f7b LTFS17228I Tape attribute: Volume Lock Status = 0x00.
f7b LTFS17227I Tape attribute: Media Pool name = .
f7b LTFS11031I Volume mounted successfully. NO_BARCODE : Gen = 25 / (a, 5) -> (b, 15859029) / HUJ312FK2J.
f7b LTFS14111I Initial setup completed successfully.
f7b LTFS14112I Invoke 'mount' command to check the result of final setup.
f7b LTFS14113I Specified mount point is listed if succeeded.`

The two sections I haven't seen before are:

`f7b LTFS30205I RSOC (0xa3) returns -20601.
f7b LTFS30263I RSOC returns Not Ready to Ready Transition, Medium May Have Changed (-20601) /dev/sg74.`

`f7b LTFS30205I READ_ATTR (0x8c) returns -20501.
f7b LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/sg74.
f7b LTFS30205I READ_ATTR (0x8c) returns -20501.
f7b LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/sg74.
f7b LTFS30205I READ_ATTR (0x8c) returns -20501.
f7b LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/sg74.
f7b LTFS30233I Cannot read attribute (-20501).`

Are any of these anything to worry about? I'm trying to be as sure as possible that this works before I start using this.

**Comment by JoakimZiegler** [comment]
@piste-jp-ibm Just as a status update, I umounted the tape, remounted it as read only, and did some test reads off of the filesystem, all in all about half a terabyte, in different files from different directories, and that all seems to work fine. So reading is ok.

I've now mounted as read/write, and I'm going to do some more testing. For what it's worth, I keep getting these lines when I mount:

```c
1603 LTFS30205I READ_ATTR (0x8c) returns -20501.
1603 LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/sg74.
1603 LTFS30205I READ_ATTR (0x8c) returns -20501.
1603 LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/sg74.
1603 LTFS30205I READ_ATTR (0x8c) returns -20501.
1603 LTFS30263I READ_ATTR returns Invalid Field in CDB (-20501) /dev/sg74.
1603 LTFS30233I Cannot read attribute (-20501).
```

But the other lines about RSOC have not appeared again. Will report back after more testing.

**Comment by piste-jp-ibm** [comment]
> Are any of these anything to worry about? I'm trying to be as sure as possible that this works before I start using this.

I don't need to worried about the messages severity `I`, last character shows the severity.

First of all, you need to understand file system (LTFS) is not working with only successful SCSI commands. Almost all commands are successfully done, but a few commands might be failed as expected.

On the other hand, the lowest level SCSI handling code doesn't know an error is not expected or unexpected in that level. So it prints the `I` level log and upper level code shows `W` or `E` level log if it is unexpected. (It is important and useful when we investigate a problem from user. Because we always want to know which SCSI command faild.)

In this case, you didn't have any `W` and `E` logs. Don't worry to much.

**Comment by piste-jp-ibm** [comment]
For `RSOC` errors (actually not error at all..), I guess you launched `ltfs` just after load a tape by hand.

The drive state might change from `loading` to `ready` between starting `ltfs` and issueing `RSOC` command. `ltfs` upper layer detected it is `not-ready-to-ready` notification and recover correctly.

**Comment by JoakimZiegler** [comment]
@piste-jp-ibm Thank you for all your help. Just as a final report, I've now copied about 6TB to a tape, and then copied various parts of that data back off of the tape and verified it, and it all looks fine, so unless there could be some very strange corner cases, I think I can say that this works fine.

**Comment by piste-jp-ibm** [comment]
Close, because no activities from 9/22.
