### ISSUE TITLE
Can't compile on Fedora 38/39

### ISSUE THREAD

**Issue by YaoFei509** [LinearTapeFileSystem/ltfs#432]
**Describe the bug**

autogen.sh and configure faild on Fedora 38/39 

`
./autogen.sh 
configure.ac:49: warning: AC_PROG_CC_C99 is obsolete; use AC_PROG_CC
configure.ac:52: warning: ac_ext=c
configure.ac:52: ac_cpp='$CPP $CPPFLAGS'
configure.ac:52: ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
configure.ac:52: ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
configure.ac:52: ac_compiler_gnu=$ac_cv_c_compiler_gnu
configure.ac:52: if test -n "$ac_tool_prefix"; then
configure.ac:52:   # Extract the first word of "${ac_tool_prefix}gcc", so it can be a program name with args.
configure.ac:52: set dummy ${ac_tool_prefix}gcc; ac_word=$2
configure.ac:52: { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
configure.ac:52: printf %s "checking for $ac_word... " >&6; }
configure.ac:52: if test ${ac_cv_prog_CC+y}
configure.ac:52: then :
configure.ac:52:   printf %s "(cached) " >&6
configure.ac:52: else $as_nop
configure.ac:52:   if test -n "$CC"; then
configure.ac:52:   ac_cv_prog_CC="$CC" # Let the user override the test.
configure.ac:52: else
configure.ac:52: as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
configure.ac:52: for as_dir in $PATH
configure.ac:52: do
configure.ac:52:   IFS=$as_save_IFS
configure.ac:52:   case $as_dir in #(((
configure.ac:52:     '' is m4_require'd but not m4_defun'd
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/programs.m4:41: _AC_CHECK_PROG is expanded from...
./lib/autoconf/programs.m4:101: AC_CHECK_PROG is expanded from...
./lib/autoconf/programs.m4:221: AC_CHECK_TOOL is expanded from...
./lib/autoconf/c.m4:452: AC_PROG_CC is expanded from...
configure.ac:52: the top level
`

**Comment by piste-jp-ibm** [comment]
They are not listed on https://github.com/LinearTapeFileSystem/ltfs#buildable-linux-distributions.

So, it's not a surprise to me.
