### ISSUE TITLE
Suggested Inclusion of RHEL Required RPMs in Documentation

### ISSUE THREAD

**Issue by JPGlaser** [LinearTapeFileSystem/ltfs#433]
**Is your feature request related to a problem? Please describe.**
There is no clear documentation for the required RPMs for the building of ltfs on RHEL distros. I was able to slowly grab requirements by debugging the configuration script and looking at the CentOS7 test build scripts.

**Describe the solution you'd like**
Add the following RPMs to the requirements section in the Wiki (as referenced by the README):
- `net-snmp-devel`, `net-snmp-libs`, `net-snmp`
- `libicu-devel`, `libicu`
- `libuuid-devel`, `libuuid`, `uuid-devel`
- `autoconf`, `libtool`, `automake`
- `fuse`, `fuse-devel` 
  - Note: Users must load the kernel module before configuring the build `modprob fuse && lsmod | grep fuse`
- `libxml2-devel`, `libxml2`

**Comment by piste-jp-ibm** [comment]
General descriptions for Linux is existing here -> https://github.com/LinearTapeFileSystem/ltfs/wiki/Build-Environments.

The packages you described is only for RHEL. I'm not sure additional description is needed or not...

**Comment by piste-jp-ibm** [comment]
Closing because there is no update for long time.
