### ISSUE TITLE
17018E xml parser unsupported encoding 'empty'  (libxml2)

### ISSUE THREAD

**Issue by weiqist** [LinearTapeFileSystem/ltfs#437]
17018E xml parser unsupported encoding 'empty' when compiled with libxml2-2.12.* 
when compiled with libxml2-2.11.* ltfs is work fine.

**Comment by main--** [comment]
Filed a bug with libxml2 because I'm not sure if the change causing this was intentional: https://gitlab.gnome.org/GNOME/libxml2/-/issues/697

**Comment by main--** [comment]
The bug was fixed in libxml2.

**Comment by piste-jp-ibm** [comment]
@main-- , 

Thanks a lot !
