### ISSUE TITLE
bug in configure

### ISSUE THREAD

**Issue by hchybz** [LinearTapeFileSystem/ltfs#438]
configure file has some syntax errors that prevent `make` to execute

line 5028 : join with next line 

```
|||  case $as_dir in #(((
|||          '') as_dir=./ ;;
```
```
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
./configure: line 5208: syntax error near unexpected token `as_dir=./'
./configure: line 5208: `    '' as_dir=./ ;;'
make: *** [Makefile:458: config.status] Error 2
```

line 6106 : extra closing ")"
 : need to be deleted

```
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
./configure: line 6106: syntax error near unexpected token `)'
./configure: line 6106: `)'
make: *** [Makefile:458: config.status] Error 2
```

**Comment by piste-jp-ibm** [comment]
`configure` script is created by the autoconf/automake system. And this boot strap is described into `autogen.sh` script in the tree. 

So, follwing info is needed additionally.

- OS, distro and it's version
- version of autoconf/autotool/libtool
- Log of `autogen.sh`
- entire log of `configure`

**Comment by piste-jp-ibm** [comment]
Closing because there is no update for long time.
