### ISSUE TITLE
ltfs_ordered_copy raising Python parsing error

### ISSUE THREAD

**Issue by TulioLazarini** [LinearTapeFileSystem/ltfs#445]
**Describe the bug**
When trying to use `ltfs_ordered_copy` to copy files to a LTFS cartridge, the following errors appear:
`Check destination:startswith first arg must be bytes or a tuple of bytes, not str` or
`object of type 'NoneType' has no len()`, depending on the usage context below. 

**To Reproduce**
1. Mount an LTFS cartridge to a given mountpoint (i.e. /mnt/ltfs)
2. Issue the ltfs_orderd_copy command, i.e.
`ltfs_ordered_copy /mnt/videos/Drama/Murder*.* /mnt/ltfs/Drama`
3. The following message appears:
`Check destination:startswith first arg must be bytes or a tuple of bytes, not str`
4. I've made another attempt, using a fully qualified source:
`ltfs_ordered_copy /mnt/videos/Drama/Murder\ Mubarak\ \(2024\).mkv /mnt/ltfs/Drama`
5. The the following error message appears:
`object of type 'NoneType' has no len()`
6. Also tried to use single and double quotes to specify the source, and the same error happens. 

**Expected behavior**
Copy being processed normally.

**Desktop (please complete the following information):**
 - OS: Fedora 39, kernel 6.7.9-200.fc39.x86_64
 - LTFS version:
b79 LTFS14000I LTFS starting, LTFS version 2.4.5.1 (Prelim), log level 2.
b79 LTFS14058I LTFS Format Specification version 2.4.0.
b79 LTFS14104I Launched by "ltfs -o devname=/dev/sg3 /mnt/ltfs".
b79 LTFS14105I This binary is built for Linux (x86_64).
b79 LTFS14106I GCC version is 13.2.1 20231205 (Red Hat 13.2.1-6).
b79 LTFS17087I Kernel version: Linux version 6.7.9-200.fc39.x86_64 (mockbuild@c9040d5832f245329326c60b1688b627) (gcc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6), GNU ld version 2.40-14.fc39) #1 SMP PREEMPT_DYNAMIC Wed Mar  6 19:35:04 UTC 2024 i386.
b79 LTFS17089I Distribution: Fedora release 39 (Thirty Nine).
b79 LTFS17089I Distribution: NAME="Fedora Linux".
 - Python version: 3.12.2

**Additional context**
In fact, I'm attempting to feed in a list of files generated by a dry_run of rsync, and copying them via ltfs_ordered_copy to reduce the shoeshining I'm getting by using rsync directly.

**Comment by piste-jp-ibm** [comment]
I cannot recreate this. Please confirm you installed `pyxattr`, not `xattr`. 

Install `pyxattr`
```
pip3.11 install pyxattr
```

Start LTFS
```
ltfs -o tape_backend=file -o devname=/Users/piste/ltfstape ./mnt/ltfs
```

Copy files
```
piste251:~ piste% sudo python3.11 /usr/local/bin/ltfs_ordered_copy /Users/piste/aaa/* ./mnt/ltfs
Tape order aware copy for LTFS
Destination ./mnt/ltfs is LTFS
On disk sources: 7
Source tapes: 0
Copying on 7 disk files with 1 threads
File copy from disk is on going: 7/7
Copied 7 files.
piste251:~ piste% ls ./mnt/ltfs
'Murder Mubarak (2024) 1.mkv'  'Murder Mubarak (2024) 3.mkv'  'Murder Mubarak (2024) 5.mkv'   aaa.data
'Murder Mubarak (2024) 2.mkv'  'Murder Mubarak (2024) 4.mkv'  'Murder Mubarak (2024).mkv'
```

Remove the files and copy one file
```
piste251:~ piste% rm -f ./mnt/ltfs/*
zsh: sure you want to delete all the files in /Users/piste/./mnt/ltfs [yn]? y
piste251:~ piste% sudo python3.11 /usr/local/bin/ltfs_ordered_copy /Users/piste/aaa/Murder\ Mubarak\ \(2024\).mkv ./mnt/ltfs
Tape order aware copy for LTFS
piste251:~ piste% ls ./mnt/ltfs
'Murder Mubarak (2024).mkv'
```

**Comment by TulioLazarini** [comment]
Thanks for trying and the tips provided, @piste-jp-ibm.

Here is the pip install output:

```
[tulio@skynetcore ~]$ pip install pyxattr
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyxattr in /usr/lib64/python3.12/site-packages (0.7.2)
```

So I'm afraid it was already there.
Then I've tried to mount the cartridge using the tape_backend=file as suggested, and had a message error:

```
[tulio@skynetcore ~]$ sudo ltfs -o tape_backend=file devname=/dev/sg3 /mnt/ltfs
bfa9 LTFS14000I LTFS starting, LTFS version 2.4.5.1 (Prelim), log level 2.
bfa9 LTFS14058I LTFS Format Specification version 2.4.0.
bfa9 LTFS14104I Launched by "ltfs -o tape_backend=file devname=/dev/sg3 /mnt/ltfs".
bfa9 LTFS14105I This binary is built for Linux (x86_64).
bfa9 LTFS14106I GCC version is 13.2.1 20231205 (Red Hat 13.2.1-6).
bfa9 LTFS17087I Kernel version: Linux version 6.7.9-200.fc39.x86_64 (mockbuild@c9040d5832f245329326c60b1688b627) (gcc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6), GNU ld version 2.40-14.fc39) #1 SMP PREEMPT_DYNAMIC Wed Mar  6 19:35:04 UTC 2024 i386.
bfa9 LTFS17089I Distribution: Fedora release 39 (Thirty Nine).
bfa9 LTFS17089I Distribution: NAME="Fedora Linux".
bfa9 LTFS17089I Distribution: Fedora release 39 (Thirty Nine).
bfa9 LTFS17089I Distribution: Fedora release 39 (Thirty Nine).
bfa9 LTFS14063I Sync type is "time", Sync time is 300 sec.
bfa9 LTFS17085I Plugin: Loading "file" tape backend.
bfa9 LTFS17085I Plugin: Loading "unified" iosched backend.
bfa9 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
bfa9 LTFS30000I Opening a device through generic file driver (/tmp/ltfs/tape).
bfa9 LTFS30081I Getting the device directory (/tmp/ltfs49065).
bfa9 LTFS30082I No device directory is specified (/tmp/ltfs49065).
bfa9 LTFS30001I Opening a redirecting file through generic file driver (/tmp/ltfs/tape).
bfa9 LTFS30002E Cannot open redirecting file (/tmp/ltfs/tape).
bfa9 LTFS12012E Cannot open device: failed backend open call.
bfa9 LTFS10004E Cannot open device '/tmp/ltfs/tape'.
[tulio@skynetcore ~]$ sudo ltfs -o tape_backend=file devname=/dev/sg3 /mnt/ltfs
bfb6 LTFS14000I LTFS starting, LTFS version 2.4.5.1 (Prelim), log level 2.
bfb6 LTFS14058I LTFS Format Specification version 2.4.0.
bfb6 LTFS14104I Launched by "ltfs -o tape_backend=file devname=/dev/sg3 /mnt/ltfs".
bfb6 LTFS14105I This binary is built for Linux (x86_64).
bfb6 LTFS14106I GCC version is 13.2.1 20231205 (Red Hat 13.2.1-6).
bfb6 LTFS17087I Kernel version: Linux version 6.7.9-200.fc39.x86_64 (mockbuild@c9040d5832f245329326c60b1688b627) (gcc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6), GNU ld version 2.40-14.fc39) #1 SMP PREEMPT_DYNAMIC Wed Mar  6 19:35:04 UTC 2024 i386.
bfb6 LTFS17089I Distribution: Fedora release 39 (Thirty Nine).
bfb6 LTFS17089I Distribution: NAME="Fedora Linux".
bfb6 LTFS17089I Distribution: Fedora release 39 (Thirty Nine).
bfb6 LTFS17089I Distribution: Fedora release 39 (Thirty Nine).
bfb6 LTFS14063I Sync type is "time", Sync time is 300 sec.
bfb6 LTFS17085I Plugin: Loading "file" tape backend.
bfb6 LTFS17085I Plugin: Loading "unified" iosched backend.
bfb6 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
bfb6 LTFS30000I Opening a device through generic file driver (/tmp/ltfs/tape).
bfb6 LTFS30081I Getting the device directory (/tmp/ltfs49078).
bfb6 LTFS30082I No device directory is specified (/tmp/ltfs49078).
bfb6 LTFS30001I Opening a redirecting file through generic file driver (/tmp/ltfs/tape).
bfb6 LTFS30002E Cannot open redirecting file (/tmp/ltfs/tape).
bfb6 LTFS12012E Cannot open device: failed backend open call.
bfb6 LTFS10004E Cannot open device '/tmp/ltfs/tape'.
```

I have removed the tape_backend parameter and the mount went just fine.
Then I've tried again the ltfs_ordered_copy calling python3.12 explicitly, to no avail, unfortunately:

```
[tulio@skynetcore ~]$ sudo python3.12 /usr/local/bin/ltfs_ordered_copy /mnt/videos/Comédia/Murder*.* /mnt/ltfs/Comédia
Tape order aware copy for LTFS
Check destination:startswith first arg must be bytes or a tuple of bytes, not str
```
Your input would be much appreciated.

**Comment by piste-jp-ibm** [comment]
Hmm, never recreated on my env (MacOS Sonoma + brewed python3.12)

```
piste251:~ piste% sudo /Users/piste/python3.12/bin/python3.12 /usr/local/bin/ltfs_ordered_copy /Users/piste/aaa/Murder*.* ./mnt/ltfs
Tape order aware copy for LTFS
Destination ./mnt/ltfs is LTFS
On disk sources: 6
Source tapes: 0
Copying on 6 disk files with 1 threads
File copy from disk is on going: 6/6
Copied 6 files.
```

**Comment by piste-jp-ibm** [comment]
The line might be below. Please investigate what happens by yourself.

https://github.com/LinearTapeFileSystem/ltfs/blob/f36304e66f06f53281fadbcebc35615b0419b3f0/src/utils/ltfs_ordered_copy#L373

**Comment by TulioLazarini** [comment]
Hello @piste-jp-ibm , here's what I did on an attempt to find the root cause of the error:

1. I've added the following lines to print the parameters being sent to ``xattr.get()`` in order to issue the command interactively and see the output:

```
    logger.info("args.DEST:    {}".format(args.DEST))
    logger.info("VEA_PREFIX:   {}".format(VEA_PREFIX))
    logger.info("LTFS_SIG_VEA: {}".format(LTFS_SIG_VEA))
```

2. Saved the program, gave it a go and got the following output (the parameters I needed for step 3):

```
[tulio@skynetcore ~]$ /usr/local/bin/ltfs_ordered_copy --verbose=6 /mnt/videos/Desenhos/Migration\ \(2023\).* /mnt/ltfs/Desenhos
Tape order aware copy for LTFS
Source (args): ['/mnt/videos/Desenhos/Migration (2023).jpg', '/mnt/videos/Desenhos/Migration (2023).mkv', '/mnt/videos/Desenhos/Migration (2023).srt']
Destination:   /mnt/ltfs/Desenhos
Checking destination is LTFS or not
args.DEST:    /mnt/ltfs/Desenhos
VEA_PREFIX:   user.
LTFS_SIG_VEA: ltfs.softwareProduct
Check destination:startswith first arg must be bytes or a tuple of bytes, not str
```

3. I've started python and tried to run xattr.get manually through CLI. That was interesting:

```
[tulio@skynetcore ~]$ python3.12
Python 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xattr
>>> xattr.get("/mnt/ltfs/Desenhos","user.ltfs.softwareProduct")
b'LTFS LE'
>>> str(xattr.get("/mnt/ltfs/Desenhos","user.ltfs.softwareProduct"))
"b'LTFS LE'"
>>> quit()
```

Please note the output for ``xattr.get()`` is now some kind of a binary type, not a regular string as it was supposed to be. When I tried to ``str()`` it, the initial b and the single quotes remain in the string.

4. Then I did a quick test, and str'ed the xattr.get() in the program to avoid the type error. Now I got it working just fine, with a minor catch: the verbose outpot says the destination is not LTFS, as the ``sig.startswith()`` comarison now fails - the string commences by b', and not LTFS anymore.

Here is the output generated by the adapted code:

```
[tulio@skynetcore ~]$ /usr/local/bin/ltfs_ordered_copy --verbose=6 /mnt/videos/Desenhos/Migration\ \(2023\).* /mnt/ltfs/Desenhos
Tape order aware copy for LTFS
Source (args): ['/mnt/videos/Desenhos/Migration (2023).jpg', '/mnt/videos/Desenhos/Migration (2023).mkv', '/mnt/videos/Desenhos/Migration (2023).srt']
Destination:   /mnt/ltfs/Desenhos
Checking destination is LTFS or not
args.DEST:    /mnt/ltfs/Desenhos
VEA_PREFIX:   user.
LTFS_SIG_VEA: ltfs.softwareProduct
Destination /mnt/ltfs/Desenhos is not LTFS

Creating copy item for file /mnt/videos/Desenhos/Migration (2023).jpg
Creating copy item for file /mnt/videos/Desenhos/Migration (2023).mkv
Creating copy item for file /mnt/videos/Desenhos/Migration (2023).srt
On disk sources: 3
Source tapes: 0
Copying on 3 disk files with 8 threads
"/mnt/videos/Desenhos/Migration (2023).jpg" -> "/mnt/ltfs/Desenhos"
"/mnt/videos/Desenhos/Migration (2023).mkv" -> "/mnt/ltfs/Desenhos"
"/mnt/videos/Desenhos/Migration (2023).srt" -> "/mnt/ltfs/Desenhos"
Index error break.
Index error break.
Index error break.
Index error break.
Index error break.
Index error break.
Index error break.
Index error break.
Copied 3 files. 
```
 
Newbie guess: I'm afraid Kernel 6.7 might have changed how xattrs are handled by pyxattr. Is this something you can give me any hint/direction?

Cheers.

**Comment by TulioLazarini** [comment]
Anyway, I was comapring my ltfs_ordered_copy with the one from the master branch, and somehow my program was corrupted. I've downloaded the latest and greatest from master, and everything is working as a treat. Sorry for bothering you, sir.
