### ISSUE TITLE
LTO9 Tape Drive fails to mount a successfully formatted LTO8 media

### ISSUE THREAD

**Issue by tonyperk** [LinearTapeFileSystem/ltfs#471]
**Describe the bug**
mkltfs run has been run on LTO9 tape drive that has LTO8 Tape Media (000001L8) and runs successfully. There are output errors related to:
cannot get remaining capacity log page x17 failed
But it successfully wrote the index to partition a and b. And it states it is successfully formatted.

Then running ltfs, it states that it cannot mount the volume due it not being partitioned.

**To Reproduce**
1. Run mkltfs on LTO9 tape drive with LTO8 media.
2. Run ltfs on /dev/IBMtape1 device that is LTO9 tape drive with the LTO8 media
3. See error

**Expected behavior**
Expect the ltfs to be able to mount the successfully formatted tape.

**Desktop (please complete the following information):**
 - OS: Rocky Linux 8.4

Lintape: 3.0.59
ltfs: 2.4.5.0

**Comment by piste-jp** [comment]
Please read the [quick start](https://github.com/LinearTapeFileSystem/ltfs/wiki/Quick-start) document before opening an issue. As it says you need to use a `sg` device instead.

Support of `lin_tape` was dropped in many years ago. I'm not sure why you want to use it at this time.

Please contact to IBM if you are using IBM provided pre-compiled version of the LTFS.

**Comment by tonyperk** [comment]
I'm using a build from 2.4.5 which was at least 5 years ago.

Also I have code that sends inquiry and TURs to sg device for health checks. So I cannot use sg device for ltfs. Also I still u see r lintape driver.

This should still work, no? It works with LTO 7 and LTO 8 tape drives. Just not LTO 9 tape drives.

**Comment by piste-jp** [comment]
> Also I have code that sends inquiry and TURs to sg device for health checks. So I cannot use sg device for ltfs. Also I still u see r lintape driver.
> 
> This should still work, no? It works with LTO 7 and LTO 8 tape drives. Just not LTO 9 tape drives.

I believe the `lin_tape` driver backend was no more maintained when 2.4.5 is released. You are just lucky to be able to use it on LTO7 and LTO8. Please do not expect same quality on using an unofficial manner.

One more thing, I strongly recommend that you should not access to the same device with different device files. It could cause a catastrophic result against data on tape. For example #446, we never say LTFS works in such kind of condition at all.

**Comment by tonyperk** [comment]
How do you address multipath devices? IBMtapeX supported multi path and sg does not.

**Comment by piste-jp** [comment]
Data path failover is already supported on the sg backend.

Please see PR #27 and 
https://github.com/LinearTapeFileSystem/ltfs/commit/a23c6da1b64fe5d9c3b27bedd22b32f8dba67a24.

**Comment by tonyperk** [comment]
That's very good news that we now have sg-ibmtape data path failover.
What about multi-path from a tape library? That is something that lin_tape was able to provide.

**Comment by piste-jp** [comment]
I'm not sure what kind of answer you are expecting but `IBM Spectrum Archive Library Edition` supports control path failover on it's sg backend for library, I think.

But it is not related into this LTFS project at all because this LTFS project is targeting only stand alone drive. So you need to contact IBM if you have an answer.
