### ISSUE TITLE
Build failed on a fresh Rocky 8.10

### ISSUE THREAD

**Issue by mildis** [LinearTapeFileSystem/ltfs#476]
Hi,

I'm desperately trying to build 2.4.6.2 on a fresh Rocky 8.10 setup.
Dependencies are installed, autogen.sh and configure succeed.
During make, message generation seems to fail despite .a files being created : 
```Processing bin_mkltfs
genrb number of files: 3
Unable to open or read "/usr/lib/x86_64-linux-gnu/icu/pkgdata.inc" option file. status = U_FILE_ACCESS_ERROR
sh: oma.c : commande introuvable
-- return status = 32512
Failed to compile oma.c
sh: ./bin_mkltfs.: No such file or directory
-- return status = 32512
Error generating library file. Failed command:   ./bin_mkltfs. ./bin_mkltfs_dat.o
Error generating package data.
```
```file messages/libbin_ltfs_dat.a 
$ file messages/libbin_ltfs_dat.a 
messages/libbin_ltfs_dat.a: ELF 32-bit MSB *unknown arch 0x300* (SYSV)
```

This lead to build failing
```*** Warning: Linking the shared library libltfs.la against the
*** static library ../../messages/liblibltfs_dat.a is not portable!

*** Warning: Linking the shared library libltfs.la against the
*** static library ../../messages/libinternal_error_dat.a is not portable!

*** Warning: Linking the shared library libltfs.la against the
*** static library ../../messages/libtape_common_dat.a is not portable!
libtool: link: gcc -shared  -fPIC -DPIC  .libs/libltfs_la-ltfs.o .libs/libltfs_la-ltfs_internal.o .libs/libltfs_la-ltfs_fsops.o .libs/libltfs_la-ltfs_fsops_raw.o .libs/libltfs_la-ltfssnmp.o .libs/libltfs_la-fs.o .libs/libltfs_la-xml_common.o .libs/libltfs_la-xml_writer.o .libs/libltfs_la-xml_reader.o .libs/libltfs_la-xml_writer_libltfs.o .libs/libltfs_la-xml_reader_libltfs.o .libs/libltfs_la-label.o .libs/libltfs_la-base64.o .libs/libltfs_la-tape.o .libs/libltfs_la-iosched.o .libs/libltfs_la-dcache.o .libs/libltfs_la-kmi.o .libs/libltfs_la-pathname.o .libs/libltfs_la-index_criteria.o .libs/libltfs_la-xattr.o .libs/libltfs_la-ltfslogging.o .libs/libltfs_la-ltfstrace.o .libs/libltfs_la-ltfs_thread.o .libs/libltfs_la-config_file.o .libs/libltfs_la-plugin.o .libs/libltfs_la-periodic_sync.o arch/.libs/libltfs_la-uuid_internal.o arch/.libs/libltfs_la-filename_handling.o arch/.libs/libltfs_la-time_internal.o arch/.libs/libltfs_la-arch_info.o arch/.libs/libltfs_la-errormap.o   -lfuse -luuid -lxml2 -licuuc -licudata -L/usr/lib64 -lnetsnmpmibs -lsensors -ldl -lrpm -lrpmio -lnetsnmpagent -lm -lnetsnmp -lssl -lcrypto ../../messages/liblibltfs_dat.a ../../messages/libinternal_error_dat.a ../../messages/libtape_common_dat.a -lrt -lpthread  -g -O2 -O0 -ggdb -Wl,--no-undefined -Wl,--as-needed -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--enable-new-dtags -Wl,-z -Wl,relro -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z -Wl,relro -Wl,-z -Wl,now   -pthread -Wl,-soname -Wl,libltfs.so.0 -o .libs/libltfs.so.0.0.0
make[3]: *** [Makefile:552: libltfs.la] Error 1
make[3] : on quitte le répertoire « /root/ltfs-2.4.6.2-10513/src/libltfs »
```

Do you have any tip for the build to succeed ?

Thanks.

**Comment by piste-jp** [comment]
One, It looks the message `Unable to open or read "/usr/lib...` is printed by `genrb` command provided from ICU package. Please contact to the ICU project.

Two, could you provide a log of the procedure below for fetching error message of the linker ?

1. `cd src/libltfs`
2. `gcc -shared  -fPIC -DPIC  .libs/libltfs_la-ltfs.o .libs/libltfs_la-ltfs_internal.o .libs/libltfs_la-ltfs_fsops.o .libs/libltfs_la-ltfs_fsops_raw.o .libs/libltfs_la-ltfssnmp.o .libs/libltfs_la-fs.o .libs/libltfs_la-xml_common.o .libs/libltfs_la-xml_writer.o .libs/libltfs_la-xml_reader.o .libs/libltfs_la-xml_writer_libltfs.o .libs/libltfs_la-xml_reader_libltfs.o .libs/libltfs_la-label.o .libs/libltfs_la-base64.o .libs/libltfs_la-tape.o .libs/libltfs_la-iosched.o .libs/libltfs_la-dcache.o .libs/libltfs_la-kmi.o .libs/libltfs_la-pathname.o .libs/libltfs_la-index_criteria.o .libs/libltfs_la-xattr.o .libs/libltfs_la-ltfslogging.o .libs/libltfs_la-ltfstrace.o .libs/libltfs_la-ltfs_thread.o .libs/libltfs_la-config_file.o .libs/libltfs_la-plugin.o .libs/libltfs_la-periodic_sync.o arch/.libs/libltfs_la-uuid_internal.o arch/.libs/libltfs_la-filename_handling.o arch/.libs/libltfs_la-time_internal.o arch/.libs/libltfs_la-arch_info.o arch/.libs/libltfs_la-errormap.o   -lfuse -luuid -lxml2 -licuuc -licudata -L/usr/lib64 -lnetsnmpmibs -lsensors -ldl -lrpm -lrpmio -lnetsnmpagent -lm -lnetsnmp -lssl -lcrypto ../../messages/liblibltfs_dat.a ../../messages/libinternal_error_dat.a ../../messages/libtape_common_dat.a -lrt -lpthread  -g -O2 -O0 -ggdb -Wl,--no-undefined -Wl,--as-needed -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--enable-new-dtags -Wl,-z -Wl,relro -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z -Wl,relro -Wl,-z -Wl,now   -pthread -Wl,-soname -Wl,libltfs.so.0 -o .libs/libltfs.so.0.0.0`

**Comment by mildis** [comment]
I track down the `pkgdata` error down to make_message_src.sh : error is displayed with `-m static` but not without this parameter (which then default to common/archive)
I also tried to install libicu50 for compatibility with no luck.

Forcing path of pkgdata.inc as per https://github.com/LinearTapeFileSystem/ltfs/issues/153#issuecomment-568628105 is OK, and message generation succeed without error.

There were still the same gcc error in building but https://github.com/LinearTapeFileSystem/ltfs/issues/153#issuecomment-572861771 solved the issue.

So to me, it is required to apply #153 to build on Rocky 8 too.
