### ISSUE TITLE
Issue: Can't mount tape on Ubuntu (SG backend)

### ISSUE THREAD

**Issue by rzerres** [LinearTapeFileSystem/ltfs#51]
# Mounting a formatted tape via sg backend breaks

using mkltfs i can format a given tape via the sg backend (sg-ibmtape driver).
Partitions (a and b) are created. Volume UUID is assigned. Volumes capacity is shown. 
As stated from the binary the mkltfs call seems completely wrokout.

a following ltfs call terminates with an read block fauillure message (-21719). Driver encounters a length mismatch detection (LTFS30216W) and therefore can't read the label from partition 0. Mounting is aborted.

What did i miss?
Do not hesitate, if you need more/precise information. Thanks

# Steps to reproduce the behavior:
1. running as root (uid=0)
1. configured /etc/ltfs.conf (namely: plugin tape sg /usr/lib/x86_64-linux-gnu/ltfs/libtape-sg-ibmtape.so, default tape sg)
1. configured /etc/ltfs.conf.local (namely:  option work_directory /run/user/0/ltfs)
  same effect, if i do keep the systemd default (/tmp/ltfs)
1. calling mkltfs 
  mkltfs -d /dev/sg9 -f -n tape009 (exit code 0)
1. create mountpoint (/media/tape)
   mkdir -p /media/tape
1. calling ltfs
  ltfs -o devname=/dev/sg9,verbose=2  /media/tape

# Expected behavior
the formatted tape should be mounted at /media/tape.

# Loggin information
1. mkltfs call
mkltfs -d /dev/sg9 -f -n tape009
LTFS15000I Starting mkltfs, LTFS version 2.4.0.1 (10062), log level 2.
LTFS15041I Launched by "mkltfs -d /dev/sg9 -f -n tape009".
LTFS15042I This binary is built for Linux (x86_64).
LTFS15043I GCC version is 7.3.0.
LTFS17087I Kernel version: Linux version 4.11.0-14-generic (buildd@lcy01-08) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 i386.
LTFS17089I Distribution: NAME="Ubuntu".
LTFS17089I Distribution: DISTRIB_ID=Ubuntu.
LTFS15003I Formatting device '/dev/sg9'.
LTFS15004I LTFS volume blocksize: 524288.
LTFS15005I Index partition placement policy: None.
LTFS11337I Update index-dirty flag (1) - NO_BARCODE (0x0x36ad5a1ac0).
LTFS17085I Plugin: Loading "sg" tape backend.
LTFS30209I Opening a device through sg-ibmtape driver (/dev/sg9).
LTFS30207I Vendor ID is IBM     .
LTFS30208I Product ID is ULTRIUM-HH7     .
LTFS30214I Firmware revision is FA17.
LTFS30215I Drive serial is 10WT030737.
LTFS17160I Maximum device block size is 1048576.
LTFS11330I Loading cartridge.
LTFS30252I Logical block protection is disabled.
LTFS11332I Load successful.
LTFS17157I Changing the drive setting to write-anywhere mode.
LTFS15049I Checking the medium (load).
LTFS30252I Logical block protection is disabled.
LTFS15010I Creating data partition b on SCSI partition 1.
LTFS15011I Creating index partition a on SCSI partition 0.
LTFS17165I Resetting the medium's capacity proportion.
LTFS11097I Partitioning the medium.
LTFS30263I MODESELECT returns Mode Parameters Rounded (-20101) /dev/sg9.
LTFS11100I Writing label to partition b.
LTFS11278I Writing index to partition b.
LTFS17235I Writing index of NO_BARCODE to b (Reason: Format, 0 files) 10WT030737.
LTFS17236I Wrote index of NO_BARCODE (b, 10WT030737).
LTFS11337I Update index-dirty flag (0) - NO_BARCODE (0x0x36ad5a1ac0).
LTFS11100I Writing label to partition a.
LTFS11278I Writing index to partition a.
LTFS17235I Writing index of NO_BARCODE to a (Reason: Format, 0 files) 10WT030737.
LTFS17236I Wrote index of NO_BARCODE (a, 10WT030737).
LTFS15013I Volume UUID is: dbcbe63b-6785-4e2a-8594-0d6565c0aba2.
LTFS15019I Volume capacity is 5732 GB.
LTFS30252I Logical block protection is disabled.
LTFS15024I Medium formatted successfully.

1. ltfs call
ltfs -o devname=/dev/sg9,verbose=2  /media/tape
104e LTFS14000I LTFS starting, LTFS version 2.4.0.1 (10062), log level 2.
104e LTFS14058I LTFS Format Specification version 2.4.0.
104e LTFS14104I Launched by "ltfs -o devname=/dev/sg9,verbose=2 /media/tape".
104e LTFS14105I This binary is built for Linux (x86_64).
104e LTFS14106I GCC version is 7.3.0.
104e LTFS17087I Kernel version: Linux version 4.11.0-14-generic (buildd@lcy01-08) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 i386.
104e LTFS17089I Distribution: NAME="Ubuntu".
104e LTFS17089I Distribution: DISTRIB_ID=Ubuntu.
104e LTFS14063I Sync type is "time", Sync time is 300 sec.
104e LTFS17085I Plugin: Loading "sg" tape backend.
104e LTFS17085I Plugin: Loading "unified" iosched backend.
104e LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
104e LTFS30209I Opening a device through sg-ibmtape driver (/dev/sg9).
104e LTFS30207I Vendor ID is IBM     .
104e LTFS30208I Product ID is ULTRIUM-HH7     .
104e LTFS30214I Firmware revision is FA17.
104e LTFS30215I Drive serial is 10WT030737.
104e LTFS17160I Maximum device block size is 1048576.
104e LTFS11330I Loading cartridge.
104e LTFS30252I Logical block protection is disabled.
104e LTFS11332I Load successful.
104e LTFS17157I Changing the drive setting to write-anywhere mode.
104e LTFS11005I Mounting the volume.
104e LTFS30252I Logical block protection is disabled.
104e LTFS30216W Length mismatch is detected. (Act = 4096, resid = 0, resid_sense = 4016).
104e LTFS12049E Cannot read: backend call failed (-21716).
104e LTFS11174E Cannot read ANSI label: read failed (-21716).
104e LTFS11170E Failed to read label (-21716) from partition 0.
104e LTFS11009E Cannot read volume: failed to read partition labels.
104e LTFS14013E Cannot mount the volume.
104e LTFS30252I Logical block protection is disabled.

**Comment by piste-jp-ibm** [comment]
It looks the HBA driver makes a funny behavior. This HBA driver cannot report actual transfer length correctly. What HBA are you using?

May be you can check configuration of the HBA to support the tape device. (Actually some HBA have a configuration but it is not enabled by default.)

The only thing we can do on the code is adding the code like `SUPPORT_BUGGY_IF` in `iokit_ibmtape.c` into `_cdb_read()` in `sg_ibm_tape.c`. But this change introduce a performance degradation.

**Comment by rzerres** [comment]
We are using an ATTO HBA dedicated for the LTO loader hardware.

# Steps taken 
Meanwhile I updated to kernel version 4.15.0-22, which is the default supported version for Ubuntu 18.04 (bionic).

I ended up to pull in the ATTO supported device driver (which needed to be compiled for the underlying kernel version) .  The given version loads, devices for loader and tape are offered to the scsi_generic interface.
I ceated an udev-rule to persitently offer /dev/changer (pointing to /dev/sg11) which is used as the default device for mtx. This is working as expected. I'm able to run the needed administrative calls (inventory, status, load, unload, etc).

Again, formatting the tape with mkltfs works out. Mounting via ltfs gives same error ( LTFS30216W,  LTFS12049E)

# Driver infos
lscpi -nn  -v | grep ATTO 
0b:00.0 Serial Attached SCSI controller [0107]: ATTO Technology, Inc. Device [117c:0042]
	Subsystem: ATTO Technology, Inc. Device [117c:0046]
modinfo esas2hba
filename:       /lib/modules/4.15.0-22-generic/kernel/drivers/scsi/esas2hba/esas2hba.ko
version:        2.31.0f1
license:        Proprietary
author:         ATTO Technology
description:    esas2hba: ATTO ExpressSAS 6GB Adapter driver

# Next TODO
will recompile and add  your code example to sg_ibm_tape.c. Will send new info once i can test again.

**Comment by rzerres** [comment]
Testing on following hardware:
Hardware name: Dell Inc. PowerEdge T630/0NT78X, BIOS 2.4.2 01/09/2017
g

**Comment by rzerres** [comment]
finaly i could implement the needed patch-set for given code. It compiles it successfully.

I did enriched the new autotools rules. Will send an PR.

I could mount tapes and have written data as expected. Wonderful!

**Comment by piste-jp-ibm** [comment]
I believe this is resolved in your patch of #52.

Please reopen this if you want to do anything on this issue.
