### ISSUE TITLE
Documentation for KMI Backend

### ISSUE THREAD

**Issue by rzerres** [LinearTapeFileSystem/ltfs#53]
# Howto use the KMI backend
The codebase states this feature experimental. Beside the source code, there is no documentation on how to use the feature yet.

# Manpage / Doc file
could you please give some short hints, on the intended usage?
I'd be glad to help out writing a manpage or markup text.

# Relation / relevance
In Europe, we have to address the "Datenschutz-Grundverordnung" (EU-DSGVO) which have been requested law since 25.05.2018. Probably quite a lot of IT professionals have to address the need to protect personal data. And tapes beeing outside the secured office environment are an active target in terms of the EU-DSGVO. Thanks

"Datenschutverordnung  since I'd like to use

**Comment by piste-jp-ibm** [comment]
I think you are talking about GDPR. Right? It is interesting that LTFS supports encryption aggressively for GDPR...

The current KMI backends (simple and flatfile) is actually just samples how to pass the key fro LTFS to the drive. So I don't want to disclose how to use it widely. Because (many) tape libraries provides a feature to encrypt data on tape transparently with keeping portability of cartridge. Most of cases, libraries provide such functionality with key server.

On the other hand, the feature in the current KMI backends does not support any key server. So you might decrypt data on tape if you write encrypted data by LTFS and import it to library.

My wish around this feature is to develop the KMI backend supports KMIP protocol. If we can do it, the encrypted tape created by LTFS can be imported to the libararies which supports KMIP protocol.

**Comment by rzerres** [comment]
Right, GDPR is correct.

Your Idea sound very reasonable. I have never heard aboiut KMIP before, but have never bothered with it.

Are you activly forcing the devolopment?
Is there any scheduled date?

**Comment by piste-jp-ibm** [comment]
I can't say anything about plans/schedule of IBM internal. And I don't have any information I can disclose here at this time.

The things I can say are
 - I am one of persons who build a plan/roadmap of LTFS in IBM internal
 - May be I need to convince other guys (internal/external of LTFS team) to develop new KMI that it contributes to the business of IBM

**Comment by piste-jp-ibm** [comment]
Let me go back to your first question.  How to use KMI plugins. I will describe it for your debug...

**Comment by piste-jp-ibm** [comment]
# Overall

You need manage a `KEY`  as a pair of an encryption key (base64 encoded 256-bit binary, DK[DataKey]) and an key index (3 alphabets + 18digits-hexadecimal text, DKi[DataKeyIndex]) in LTFS. 

For example,
 - DKi: `IBM0123456789abcdef01`
 - DK: `YAwK8AGgc/Q6vHt6LoMwz9wlI0wTOLsPsmqxWmLygek=` 

LTFS store `KEY` information to memory at start time and use them when it is required.

## Mount

In the mount sequence, LTFS tries to read tape without keys at first. And the tape drive will return error with used DKi to LTFS. So LTFS sets back correct DK (searched from returned DKi) to the tape drive and retry read. 

## Format

In the format process, `mkltfs` may check contents of tape before format to avoid unexpected format. So old `KEY` information to decrypt current contents and new `KEY` information to create new format is required.

# "simple" plugin

## Format

Case1 [the tape is not encrypted]:

`mkltfs -d /dev/sgx --kmi-backend=simple -o kmi_dki_for_format=IBM0123456789abcdef01 -o kmi_dk_for_format=YAwK8AGgc/Q6vHt6LoMwz9wlI0wTOLsPsmqxWmLygek=`

Case2 [the tape is encrypted by IBM10fedcba9876543210]:

`mkltfs -d /dev/sgx --kmi-backend=simple -o kmi_dki=IBM10fedcba9876543210 -o kmi_dk=k0I1gsz9Vm3kHOPeTx02AuOGAwfWZFfvK7U76CNTGwg= -o kmi_dki_for_format=IBM0123456789abcdef01 -o kmi_dk_for_format=YAwK8AGgc/Q6vHt6LoMwz9wlI0wTOLsPsmqxWmLygek=`

## Mount 

`ltfs -o devname=/dev/sgx -o kmi_backend=simple -o kmi_dki=IBM0123456789abcdef01 -o kmi_dk=YAwK8AGgc/Q6vHt6LoMwz9wlI0wTOLsPsmqxWmLygek= [mount_point]`

# "flatfile" plugin

## Key file

- You can have multiple `KEY` information in it.
- LF is the only valid return character

```
DK=YAwK8AGgc/Q6vHt6LoMwz9wlI0wTOLsPsmqxWmLygek=
DKi=IBM0123456789abcdef01
DK=k0I1gsz9Vm3kHOPeTx02AuOGAwfWZFfvK7U76CNTGwg=
DKi=IBM10fedcba9876543210
```

## Format

Case1 [the tape is not encrypted]:

`mkltfs -d /dev/sgx --kmi-backend=flatfile -o kmi_dk_list=[path_to_key_file] -o kmi_dki_for_format=IBM0123456789abcdef01`

Case2 [the tape is encrypted by IBM10fedcba9876543210]:

`mkltfs -d /dev/sgx --kmi-backend=flatfile -o kmi_dk_list=[path_to_key_file] -o kmi_dki=IBM10fedcba9876543210 -o kmi_dki_for_format=IBM0123456789abcdef01`

## Mount

`ltfs -o devname=/dev/sgx -o kmi_backend=flatfile -o kmi_dk_list=[path_to_key_file] -o kmi_dki=IBM0123456789abcdef01 [mount_point]`

**Comment by piste-jp-ibm** [comment]
KMI description was added to Wiki.
