### ISSUE TITLE
Linking problem in ArchLinux

### ISSUE THREAD

**Issue by rzerres** [LinearTapeFileSystem/ltfs#54]
# Can't link compiled code 
I did successfully compile the code in ArchLinux (configure, make)
When linking, process stops with following error message. (make install)

# Compile environment
gcc (GCC) 8.1.1 20180531
GNU ld (GNU Binutils) 2.30
makedepends=('git' 'make' 'fuse' 'libxml2' 'icu' 'libutil-linux' 'net-snmp')

./autogen.sh
DEFAULT_TAPE=sg ./configure \
	      --enable-buggy-ifs \
	      --prefix=/usr
retun: ok
 make DESTDIR="/tmp/" install

# Compile/Linker error
libtool: relink: gcc -shared  -fPIC -DPIC  .libs/libtape_file_la-filedebug_tc.o .libs/libtape_file_la-filedebug_conf_tc.o .libs/libtape_file_la-ibm_tape.o   -L/usr/lib -L../../../../messages/ -ltape_generic_file_dat -L/data/development/ltfs_ibm/pkg/usr/lib -lltfs -L../../messages -lfuse -luuid -lxml2 -licui18n -licuuc -licudata -lnetsnmpmibs -lpci -ldl -lnetsnmpagent -lnetsnmp -lcrypto -lnl-3 -lm -llibltfs_dat -linternal_error_dat -ltape_common_dat -lrt -lpthread  -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -O2 -g -Wl,--no-undefined -Wl,--as-needed -pthread -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-E -Wl,-rpath -Wl,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now   -pthread -Wl,-soname -Wl,libtape-file.so -o .libs/libtape-file.so
.libs/libtape_file_la-filedebug_conf_tc.o: In function `_filedebug_parser_init':
/data/development/ltfs_ibm/src/ltfs/src/tape_drivers/generic/file/filedebug_conf_tc.c:191: undefined reference to `xml_next_tag'
.libs/libtape_file_la-filedebug_conf_tc.o: In function `_filedebug_tc_parse_schema':
/data/development/ltfs_ibm/src/ltfs/src/tape_drivers/generic/file/filedebug_conf_tc.c:223: undefined reference to `xml_next_tag'

**Comment by piste-jp-ibm** [comment]
`xml_next_tag()` is defined in src/libltfs/xml_reader.c.

It looks little bit funny the command line has `-lltfs` but linker doesn't find `xml_next_tag()`. Is libltfs.so is correctly generated?

**Comment by piste-jp-ibm** [comment]
I confirmed the tree (4aa7c732f09175bd2edb280de1ffadadc00b7e9d) can be built and can be installed on ArchLinux 2018.08.01.
