### ISSUE TITLE
Can IBM Spectrum Archive release space from deleted files?

### ISSUE THREAD

**Issue by hrchu** [LinearTapeFileSystem/ltfs#56]

**Comment by piste-jp-ibm** [comment]
First of all, you can read the manual of "IBM Spectrum Archive SDE 2.4". I think there is answer [here](https://www.ibm.com/support/knowledgecenter/en/STQNYL_2.4.0/ltfs_hints_overwrite_erase.html).

I believe the question is little bit unclear. Please clarify your scenario to reclaim space.
