### ISSUE TITLE
Can't mount tape.

### ISSUE THREAD

**Issue by tanakatakuo** [LinearTapeFileSystem/ltfs#74]
I installed ltfs software on my PC with IBM LTO-6 drive (ULT3580-TD6).

OS: CentOS Linux release 7.3.1611 (Core)
Kernel: Linux version 3.10.0-514.el7.x86_64 

In my case, LTO drive is assigned to /dev/sg2 as blow.

     >ltfs -o device_list
     9a9 LTFS14000I LTFS starting, LTFS version 2.4.1.0 (Prelim), log level 2.
     9a9 LTFS14058I LTFS Format Specification version 2.4.0.
     9a9 LTFS14104I Launched by "ltfs -o device_list".
     9a9 LTFS14105I This binary is built for Linux (x86_64).
     9a9 LTFS14106I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-28).
     9a9 LTFS17087I Kernel version: Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016 i386.
     9a9 LTFS17089I Distribution: CentOS Linux release 7.3.1611 (Core) .
     9a9 LTFS17089I Distribution: NAME="CentOS Linux".
     9a9 LTFS17089I Distribution: CentOS Linux release 7.3.1611 (Core) .
     9a9 LTFS17089I Distribution: CentOS Linux release 7.3.1611 (Core) .
     9a9 LTFS17085I Plugin: Loading "sg" tape backend.
     Tape Device list:.
     Device Name = /dev/sg2, Vender ID = IBM     , Product ID = ULT3580-TD6     , Serial Number = 1068007767, Product Name =[ULT3580-TD6].
     

I could format the LTO tape successfully, but mounting the tape was failed as following.

[[ Tape Format ]]

     >mkltfs -f -d /dev/sg2
     LTFS15000I Starting mkltfs, LTFS version 2.4.1.0 (Prelim), log level 2.
     LTFS15041I Launched by "mkltfs -f -d /dev/sg2".
     LTFS15042I This binary is built for Linux (x86_64).
     LTFS15043I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-28).
     LTFS17087I Kernel version: Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016 i386.
     LTFS17089I Distribution: CentOS Linux release 7.3.1611 (Core) .
     LTFS17089I Distribution: NAME="CentOS Linux".
     LTFS17089I Distribution: CentOS Linux release 7.3.1611 (Core) .
     LTFS17089I Distribution: CentOS Linux release 7.3.1611 (Core) .
     LTFS15003I Formatting device '/dev/sg2'.
     LTFS15004I LTFS volume blocksize: 524288.
     LTFS15005I Index partition placement policy: None.
     LTFS11337I Update index-dirty flag (1) - NO_BARCODE (0x0x257cdd0).
     LTFS17085I Plugin: Loading "sg" tape backend.
     LTFS30209I Opening a device through sg-ibmtape driver (/dev/sg2).
     LTFS30207I Vendor ID is IBM     .
     LTFS30208I Product ID is ULT3580-TD6     .
     LTFS30214I Firmware revision is C9T4.
     LTFS30215I Drive serial is 1068007767.
     LTFS17160I Maximum device block size is 1048576.
     LTFS11330I Loading cartridge.
     LTFS30252I Logical block protection is disabled.
     LTFS11332I Load successful.
     LTFS17157I Changing the drive setting to write-anywhere mode.
     LTFS15049I Checking the medium (load).
     LTFS30252I Logical block protection is disabled.
     LTFS15010I Creating data partition b on SCSI partition 1.
     LTFS15011I Creating index partition a on SCSI partition 0.
     LTFS17165I Resetting the medium's capacity proportion.
     LTFS11097I Partitioning the medium.
     LTFS30263I MODESELECT returns Mode Parameters Rounded (-20101) /dev/sg2.
     LTFS11100I Writing label to partition b.
     LTFS11278I Writing index to partition b.
     LTFS17235I Writing index of NO_BARCODE to b (Reason: Format, 0 files) 1068007767.
     LTFS17236I Wrote index of NO_BARCODE (b, 1068007767).
     LTFS11337I Update index-dirty flag (0) - NO_BARCODE (0x0x257cdd0).
     LTFS11100I Writing label to partition a.
     LTFS11278I Writing index to partition a.
     LTFS17235I Writing index of NO_BARCODE to a (Reason: Format, 0 files) 1068007767.
     LTFS17236I Wrote index of NO_BARCODE (a, 1068007767).
     LTFS15013I Volume UUID is: 93c85bf5-c9a3-4a81-9e37-7601699c4311.
     LTFS15019I Volume capacity is 2408 GB.
     LTFS30252I Logical block protection is disabled.
     LTFS15024I Medium formatted successfully.

[[ Mount ]]

     ltfs -o devname=/dev/sg2 /mnt/ltfs6
     9ad LTFS14000I LTFS starting, LTFS version 2.4.1.0 (Prelim), log level 2.
     9ad LTFS14058I LTFS Format Specification version 2.4.0.
     9ad LTFS14104I Launched by "ltfs -o devname=/dev/sg2 /mnt/ltfs6".
     9ad LTFS14105I This binary is built for Linux (x86_64).
     9ad LTFS14106I GCC version is 4.8.5 20150623 (Red Hat 4.8.5-28).
     9ad LTFS17087I Kernel version: Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016 i386.
     9ad LTFS17089I Distribution: CentOS Linux release 7.3.1611 (Core) .
     9ad LTFS17089I Distribution: NAME="CentOS Linux".
     9ad LTFS17089I Distribution: CentOS Linux release 7.3.1611 (Core) .
     9ad LTFS17089I Distribution: CentOS Linux release 7.3.1611 (Core) .
     9ad LTFS14063I Sync type is "time", Sync time is 300 sec.
     9ad LTFS17085I Plugin: Loading "sg" tape backend.
     9ad LTFS17085I Plugin: Loading "unified" iosched backend.
     9ad LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
     9ad LTFS30209I Opening a device through sg-ibmtape driver (/dev/sg2).
     9ad LTFS30207I Vendor ID is IBM     .
     9ad LTFS30208I Product ID is ULT3580-TD6     .
     9ad LTFS30214I Firmware revision is C9T4.
     9ad LTFS30215I Drive serial is 1068007767.
     9ad LTFS17160I Maximum device block size is 1048576.
     9ad LTFS11330I Loading cartridge.
     9ad LTFS30252I Logical block protection is disabled.
     9ad LTFS11332I Load successful.
     9ad LTFS17157I Changing the drive setting to write-anywhere mode.
     9ad LTFS11005I Mounting the volume.
     9ad LTFS30252I Logical block protection is disabled.
     9ad LTFS30216W Length mismatch is detected. (Act = 4096, resid = 0, resid_sense = 4016).
     9ad LTFS12049E Cannot read: backend call failed (-21716).
     9ad LTFS11174E Cannot read ANSI label: read failed (-21716).
     9ad LTFS11170E Failed to read label (-21716) from partition 0.
     9ad LTFS11009E Cannot read volume: failed to read partition labels.
     9ad LTFS14013E Cannot mount the volume.
     9ad LTFS30252I Logical block protection is disabled.

What is “Cannot read: backend call failed (-21716).”?  I feel something occurs in tape driver, but I do not know.
I appreciate very much if somebody could help and advise me.

best regards

**Comment by piste-jp-ibm** [comment]
Can you provide a information of HBA? I think this HBA doesn't handle the residual length in SCSI layer correctly. 

This issue is already reported by #51 and resolved by #52. May be LTFS can handle this case correctly if you specify `--enable-buggy-ifs` to the `configure` script and rebuild the code.

**Comment by tanakatakuo** [comment]
Dear Abe-san

I rebuild the code with option of "--enable-buggy-ifs".

I confirmed that the system is working and I could mount the media.

Thank you very much for your support.

best regards,
